### ISSUE TITLE
增加复习模式

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#100]
**刷完的课程，课程时长少1/10
注释main.py
46～50没刷时长**

**Comment by Samueli924** [comment]
课程时长少是因为超星默认不是要完成100%才算结束，而是完成90%-95%任务点就会完成，返回的json中passwd就变成了True
我之前给的建议不对，就算注释了46-50行，超星一返回Passed，程序还是会跳过。
后面我会加上运行参数，就算超星返回了passed，也一定要完成100%才结束任务。

**Comment by d4renk** [comment]
> 课程时长少是因为超星默认不是要完成100%才算结束，而是完成90%-95%任务点就会完成，返回的json中passwd就变成了True
> 我之前给的建议不对，就算注释了46-50行，超星一返回Passed，程序还是会跳过。
> 后面我会加上运行参数，就算超星返回了passed，也一定要完成100%才结束任务。

**有的课程不刷满（不足1/10），就过了，现在怎么补救**

**Comment by d4renk** [comment]
> 课程时长少是因为超星默认不是要完成100%才算结束，而是完成90%-95%任务点就会完成，返回的json中passwd就变成了True
> 我之前给的建议不对，就算注释了46-50行，超星一返回Passed，程序还是会跳过。
> 后面我会加上运行参数，就算超星返回了passed，也一定要完成100%才结束任务。

**Passed判断在哪（🐶🐶🐶）**
