### ISSUE TITLE
用ocr库 解决验证码

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#101]
pip3.9 install muggle_ocr -i https://pypi.douban.com/simple/

优点:从根源上解决验证码
缺点:muggle_ocr库近500m 编译的二进制文件过大

**因为一些原因官方已经删掉muggle_ocr，昨天豆瓣也同步删除了😂**

**Comment by DaXue403** [comment]
也许可以试试[tesseract.js](https://github.com/naptha/tesseract.js)

**Comment by Samueli924** [comment]
这些效率都太低了 tesseract成功率感人

**Comment by d4renk** [comment]
> 这些效率都太低了 tesseract成功率感人

muggle_ocr 学习通正确率在3/4左右，但找不到库了

**Comment by DaXue403** [comment]
验证码主要是四到六位字母和数字为主，效率其实不用太考虑，，
