### ISSUE TITLE
[BUG反馈] 刷课不刷学习次数

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#104]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

刷课不刷学习次数

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
debian11
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]  Python3.9
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行] 源码
 - 代码版本:[比如0.5.0,1.0.0]
2.4.1

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by daning66** [comment]
刷课的时候容易卡退，那种刷完一个章节，然后出现下一个章节的，直接卡死

**Comment by Samueli924** [comment]
后续会添加功能
