### ISSUE TITLE
【BUG反馈】没有权限访问页面

### ISSUE THREAD

**Issue by BlackGoldTitan** [Samueli924/chaoxing#107]
![屏幕截图 2022-05-08 142611](https://user-images.githubusercontent.com/52962048/167284674-1c321b4a-cb71-435c-8b98-11ca09fa5ebb.png)
<div class="main">
<p class="font_top">>_< 【9011】很抱歉，您没有权限访问这个页面！code=6  (403)</p>
<p style="font-size: 12px; color: #ddd;">221.4.43.90<br/>mooc-3882363147-89ktx</p>

**Comment by Samueli924** [comment]
请使用正常1倍速使用
