### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Hetols** [Samueli924/chaoxing#115]
**形容Bug的信息**
2022-05-26 08:56:05,662 - main - INFO - 登陆中
2022-05-26 08:56:05,662 - ChaoxingAPI - DEBUG - 发送登录数据
2022-05-26 08:56:05,869 - ChaoxingAPI - DEBUG - 收到返回数据
2022-05-26 08:56:05,869 - ChaoxingAPI - ERROR - 登录失败：{'msg2': '参数为空', 'status': False}
任务已结束，请点击回车键退出程序

**运行环境:**
 - 系统：Ubuntu 22.04
 - Python环境版本: Pyython3.10.4
 - 运行方式: 源代码运行
 - 代码版本: 2.4.1

**Comment by B1gM8c** [comment]
可以尝试修改`api/chaoxing.py`文件
记得先引入
```
from pyDes import des, PAD_PKCS5
import binascii
```

51-58行，主要是将base64加密算法修改为了DES加密算法
```
        des_obj = des("u2oh6Vu^", "u2oh6Vu^", pad=None, padmode=PAD_PKCS5)
        secret_bytes = des_obj.encrypt(self.passwd, padmode=PAD_PKCS5)
        data = {"fid": "-1",
                "uname": self.usernm,
                "password": binascii.b2a_hex(secret_bytes).decode("utf-8"),
                "t": "true",
                "forbidotherlogin": "0",
                "validate": ""}
```

**Comment by B1gM8c** [comment]
des也需要自己安装，你也可以加入到`requirements.txt`里，文件改为
```
maskpass
natsort
requests
urllib3==1.25.11
pyDes
```
然后安装依赖
```
pip install -r requirements.txt
```

**Comment by Hetols** [comment]
> des也需要自己安装，你也可以加入到`requirements.txt`里，文件改为
> 
> ```
> maskpass
> natsort
> requests
> urllib3==1.25.11
> pyDes
> ```
> 
> 然后安装依赖
> 
> ```
> pip install -r requirements.txt
> ```

修改后可以正常运行
