### ISSUE TITLE
[BUG反馈]前端密码加密更改

### ISSUE THREAD

**Issue by DaXue403** [Samueli924/chaoxing#116]
**形容Bug的信息**
目前超星更改了登录密码的加密方式，从base64更改到DES加密

**Screenshots**
![image](https://user-images.githubusercontent.com/78030250/170460921-9b94ca15-ba5e-49af-8930-9caf37bb97d3.png)
![image](https://user-images.githubusercontent.com/78030250/170460977-7c1d38b0-7600-42dc-8e7f-0c1bd3a2aadf.png)

**其他内容**
实现加密的js位于http://passport2.chaoxing.com/js/common/crypto-js.min.js
内含置换表。
可以考虑使用手机端的登录api。

**Comment by B1gM8c** [comment]
可以尝试修改`api/chaoxing.py`文件
记得先引入
```
from pyDes import des, PAD_PKCS5
import binascii
```

51-58行，主要是将base64加密算法修改为了DES加密算法
```
        des_obj = des("u2oh6Vu^", "u2oh6Vu^", pad=None, padmode=PAD_PKCS5)
        secret_bytes = des_obj.encrypt(self.passwd, padmode=PAD_PKCS5)
        data = {"fid": "-1",
                "uname": self.usernm,
                "password": binascii.b2a_hex(secret_bytes).decode("utf-8"),
                "t": "true",
                "forbidotherlogin": "0",
                "validate": ""}
```

当然des也需要自己安装，你也可以加入到`requirements.txt`里，文件改为
```
maskpass
natsort
requests
urllib3==1.25.11
pyDes
```
然后安装依赖
```
pip install -r requirements.txt
```

**Comment by DaXue403** [comment]
> 可以尝试修改`api/chaoxing.py`文件 记得先引入
> 
> ```
> from pyDes import des, PAD_PKCS5
> import binascii
> ```
> 
> 51-58行，主要是将base64加密算法修改为了DES加密算法
> 
> ```
>         des_obj = des("u2oh6Vu^", "u2oh6Vu^", pad=None, padmode=PAD_PKCS5)
>         secret_bytes = des_obj.encrypt(self.passwd, padmode=PAD_PKCS5)
>         data = {"fid": "-1",
>                 "uname": self.usernm,
>                 "password": binascii.b2a_hex(secret_bytes).decode("utf-8"),
>                 "t": "true",
>                 "forbidotherlogin": "0",
>                 "validate": ""}
> ```
> 
> 当然des也需要自己安装，你也可以加入到`requirements.txt`里，文件改为
> 
> ```
> maskpass
> natsort
> requests
> urllib3==1.25.11
> pyDes
> ```
> 
> 然后安装依赖
> 
> ```
> pip install -r requirements.txt
> ```

按原来之前有人问过了啊，，没注意
