### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by daning66** [Samueli924/chaoxing#117]
**bug登录失败参数空

**Comment by cclucky1** [comment]
我也遇到这个问题了

**Comment by B1gM8c** [comment]
参考https://github.com/Samueli924/chaoxing/pull/118

**Comment by daning66** [comment]
有打包好的没

**Comment by B1gM8c** [comment]
你可以试下这个
https://github.com/B1gM8c/chaoxing/releases/tag/2.4.1
