### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 2682856025** [Samueli924/chaoxing#121]
**形容Bug的信息**

请输入密码(已自动隐藏)出现报错<class 'termios.error'>
错误文件名：/Users/wangyuhang/Desktop/chaoxing-2.4.2/main.py
错误行数：145
错误原因:(25, 'Inappropriate ioctl for device')
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：macOS
 - Python环境版本:python3.9
 - 运行方式: 源代码运行
 - 代码版本:2.4.2

**其他内容**

**Comment by Samueli924** [comment]
请不要使用IDE的运行方式。应该使用命令行运行
