### ISSUE TITLE
[BUG反馈]出现报错<class 'requests.exceptions.ConnectionError'> 错误文件名：C:\Users\xcb\chaoxing\main.py 错误行数：152 错误原因:HTTPSConnectionPool(host='mooc1-api.chaoxing.com', port=443): Max retries exceeded with url: /mycourse/backclazzdata?view=json&mcode= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ED3D815E20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by xcb157342** [Samueli924/chaoxing#124]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/66261780/172620832-651c5dac-fad7-4437-95fa-6ed762c22903.png)

**运行环境 (请完善以下信息):**
 - 系统：windows11
 - Python环境版本:Python 3.9
 - 运行方式: 源代码运行
 - - 代码版本:2022/6/8最新

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
这个是你的网络问题导致的，你可以检查一下你的代理、DNS设置、网络连接。
