### ISSUE TITLE
[BUG反馈]序号登录时，已登录账号显示bug

### ISSUE THREAD

**Issue by eya46** [Samueli924/chaoxing#126]
**形容Bug的信息**
utils/functions.py
序号登录时，已登录账号显示bug，默认值还是120行for中的最后一位

**截图**
![bug](https://user-images.githubusercontent.com/61458340/175508657-6c31f0aa-5e27-4738-85e2-a694c4979ad3.png)

**修复**

``` python
# utils/functions.py 137行开始
with open(f"saves/{users[int(num) - 1]}/user.json", "r") as f:
    __temp = json.loads(f.read())
    usernm = __temp["usernm"]
    # 用序号选择后，没有更改sec_user，默认值还是120行for中的最后一位
    sec_user = "%s****%s" % (usernm[:3], usernm[7:])
    passwd = __temp["passwd"]
```

**其它**
咋提交代码...为啥我git提交显示没权限

**Comment by Samueli924** [comment]
感谢反馈，显示没权限有没有可能是你用错命令了呀，你可以尝试用github网页端提交代码试试。
