### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 2682856025** [Samueli924/chaoxing#128]
<img width="477" alt="截屏2022-06-25 下午9 30 03" src="https://user-images.githubusercontent.com/106012957/175775718-2234802d-418d-4d05-b814-fe301604d8dd.png">
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
请勿在IDE中直接运行代码，请使用命令行运行
