### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by hj01857655** [Samueli924/chaoxing#130]
**形容Bug的信息**
/*清楚准确的描述Bug出现的代码行数，以及上下文的日志内容*/

出现报错<class 'TypeError'>
错误文件名：C:\Users\12925\AppData\Local\Temp\_MEI116242\main.py
错误行数：182
错误原因:unsupported operand type(s) for *: 'int' and 'NoneType'
请截图提交至Github或Telegram供作者修改代码

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/48206536/177375605-3273fc45-2a46-4135-887b-0c74b194b60a.png)

**运行环境 (请完善以下信息):**
 - 系统：win11 64位
 - Python环境版本:[比如:Python3.10 64位]
 - 运行方式: [源代码运行和打包bat文件运行]
 - 代码版本:

**其他内容**
代码版课程选择器不一致

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
