### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by LIMBO42** [Samueli924/chaoxing#131]
**形容Bug的信息**

**Screenshots**
插入程序出现BUG的截图
![image-20220708212549993](https://typora-1306385380.cos.ap-nanjing.myqcloud.com/img/image-20220708212549993.png)

**运行环境 (请完善以下信息):**
 - 系统：wsl2
 - Python环境版本:python3.9
 - 运行方式: 源代码运行
 - 代码版本:最新

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by LIMBO42** [comment]
(https://typora-1306385380.cos.ap-nanjing.myqcloud.com/img/image-20220708214620777.png)
页面无法访问，获取的页面地址有问题

**Comment by LIMBO42** [comment]
感觉应该是获取章节的 fid 有问题

**Comment by FlyumMicro** [comment]
![image](https://user-images.githubusercontent.com/50798769/181877264-c91a1023-4520-44ab-ac1d-cc700f6870ce.png)
![image](https://user-images.githubusercontent.com/50798769/181877275-bf5b6116-f1b9-4a7a-a12c-847ff35809cd.png)

**Comment by sexboyliu** [comment]
![微信截图_20220730195836](https://user-images.githubusercontent.com/95696828/181909834-18c0b46f-a75b-44c1-a6e9-43e059703bda.png)
![微信截图_20220730195822](https://user-images.githubusercontent.com/95696828/181909847-6245b855-99ae-429c-9313-c8e68e8a81de.png)
也报同样的错误

**Comment by distress1023** [comment]
![image](https://user-images.githubusercontent.com/62579541/182002666-4723980f-43be-40e2-baac-eb603c31ed2e.png)

**Comment by 4649864** [comment]
报错了，怎么修复
![1659351215725](https://user-images.githubusercontent.com/106512178/182133085-b0a2327d-5634-4e29-b639-c6049e367d75.png)
呢

**Comment by 4649864** [comment]
无法使用[](url
![1659351335415](https://user-images.githubusercontent.com/106512178/182133536-99f92337-6507-4d1a-8fe1-87df5a5b1cfc.png)
)

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢

**Comment by sexboyliu** [comment]
谢谢



---原始邮件---
发件人: "Samuel ***@***.***&gt;
发送时间: 2022年9月24日(周六) 凌晨0:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Samueli924/chaoxing] [BUG反馈] (Issue #131)




 
已由a81608882于PR #142中修复。
 请尝试重新拉取代码后使用，谢谢
