### ISSUE TITLE
无法读取课程信息[BUG反馈]

### ISSUE THREAD

**Issue by wen-Uncle** [Samueli924/chaoxing#133]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/105272423/182157797-505d8bfc-a0b5-4c2e-82d7-e7171bf5730e.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 4649864** [comment]
系统：Windows 10 家庭中文版
运行方式：可执行文件exe运行
代码版本（2.4.2）反正就是最新的版本
由于bug的代码太长，只截图了开头和结尾
![捕获](https://user-images.githubusercontent.com/106512178/182383946-6c4f10f8-4d61-42cb-b29a-6e5128cefb55.PNG)
![捕获2](https://user-images.githubusercontent.com/106512178/182383947-320dd476-a092-449c-9ad2-57e1d48cc22b.PNG)

**Comment by 4649864** [comment]
系统：Windows 10 家庭中文版
Python环境版本：Python3.9
运行方式：源码运行
代码版本：导入本地的最新代码
![捕获](https://user-images.githubusercontent.com/106512178/182386122-7c3f5178-bf2e-48a9-ab32-7d685a9126ab.PNG)

**Comment by distress1023** [comment]
系统：Windows 10 家庭中文版
运行方式：可执行文件exe运行
代码版本（2.4.2）反正就是最新的版本
由于bug的代码太长，只截图了开头和结尾
![image](https://user-images.githubusercontent.com/62579541/182962738-0a8c1fcf-001c-4c7d-a332-05cb6b487ec3.png)
![image](https://user-images.githubusercontent.com/62579541/182962791-fdb906d3-dbc0-4c2e-ae74-3dbad9382e1b.png)

**Comment by abai2020** [comment]
TG群好像没了，还有更新计划吗

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

暂时未编译windows版本

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
