### ISSUE TITLE
提示没有权限

### ISSUE THREAD

**Issue by mijjjj** [Samueli924/chaoxing#134]
![image](https://user-images.githubusercontent.com/37797122/183853732-534be1ce-c835-49c6-812b-88966108986f.png)
![image](https://user-images.githubusercontent.com/37797122/183853789-1a94a4b4-8d9e-4ee6-bd96-c11c8938e5f7.png)

**Comment by awnc** [comment]
同样的问题

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
