### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by hmingv** [Samueli924/chaoxing#135]
**形容Bug的信息**
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：/app/main.py
错误行数：186
错误原因:Expecting value: line 1 column 1 (char 0)

**Screenshots**
![image](https://user-images.githubusercontent.com/57735185/183908924-4243b912-9747-41e6-a11a-37ca8814113f.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows
 - Python环境版本:Docker
 - 运行方式: Docker
 - 代码版本:最新

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

暂时未编译windows版本

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
