### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by xiaoyi7318** [Samueli924/chaoxing#136]
请输入您要学习的课程序号：11
默认倍速： 1 倍速
在不紧急的情况下建议使用 1 倍速，因使用不合理的多倍速造成的一切风险与作者无关
请输入您想要的学习倍速(倍数需为整数,0或直接回车将使用默认1倍速)：1
2022-08-13 20:28:30,592 - main - INFO - 开始学习
2022-08-13 20:28:30,593 - main - INFO - 已选课程：毛泽东思想和中国特色社会主义理论体系概论（网上考查课）
2022-08-13 20:28:30,597 - main - INFO - 开始获取所有章节
开始读取标签信息

当前章节：1.1:马克思主义只有中国化才能在中国大地上闪耀真理光芒

当前视频：1.1.mp4
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：D:\chaoxing\main.py
错误行数：187
错误原因:Expecting value: line 1 column 1 (char 0)
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

暂时未编译windows版本

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
