### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 7C2248** [Samueli924/chaoxing#138]
**Screenshots**
[插入程序出现BUG的截图](url)
![9ND7RBO$1(1547L2_ GM011](https://user-images.githubusercontent.com/99867186/186902384-a9aedd0a-8dc2-4a30-a883-f50f662f0332.png)
![HM6VT{N5K9CO%`I)`SVNO P](https://user-images.githubusercontent.com/99867186/186902390-772529f9-3d4c-44bd-9892-533e0b773b87.png)
![8Q6B3S@Z @RE{07FC`R66AD](https://user-images.githubusercontent.com/99867186/186902403-0de95f31-0068-4a18-85c5-8da5588e8b3f.png)
![S~KM47VGKU~9DIGH}5S EFW](https://user-images.githubusercontent.com/99867186/186902416-7554a691-0e64-4ef6-9be1-8fb8bf19fe6b.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows 10 专业版 21H2
 - Python环境版本:python3.9
 - 运行方式: exe运行
 - 代码版本:2.4.2

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

暂时未编译windows版本

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
