### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by AquaIndigo** [Samueli924/chaoxing#140]
**形容Bug的信息**
```
请输入您要学习的课程序号：3
默认倍速： 1 倍速 
在不紧急的情况下建议使用 1 倍速，因使用不合理的多倍速造成的一切风险与作者无关
请输入您想要的学习倍速(倍数需为整数,0或直接回车将使用默认1倍速)：
2022-08-30 15:23:33,812 - main - INFO - 开始学习
2022-08-30 15:23:33,812 - main - INFO - 已选课程：南京大学研究生新生入学教育课程
2022-08-30 15:23:33,813 - main - INFO - 开始获取所有章节
开始读取标签信息

当前章节：1.1:第一讲 南京大学研究生教育历史与现状

当前视频：第一讲.mp4
当前播放速率：1倍速
Expecting value: line 1 column 1 (char 0)
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：/home/suyao/codes/playground/chaoxing/main.py
错误行数：186
错误原因:Expecting value: line 1 column 1 (char 0)
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序
```
**Screenshots**
![image](https://user-images.githubusercontent.com/58110312/187379273-35c43786-44e7-454e-b7d4-e7f643015f7d.png)

**运行环境 (请完善以下信息):**
 - 系统：Manjaro
 - Python环境版本: Python3.10
 - 运行方式: 源码运行
 - 代码版本:2.4.2

**其他内容**
所有课程的视频都不行

**Comment by xxxxxy211** [comment]
哈哈我也是这个问题

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by AquaIndigo** [comment]
> git clone https://github.com/cyear/chaoxing.git 这个，目前暂时修复，这个问题还是有，最近几天再看看

这边已经可以用了
