### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by AlwaysLazy21** [Samueli924/chaoxing#141]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容            刷课时出现错误
**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/95759005/187464296-a82e339a-5693-4600-80ff-b77c72cfbe94.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]          windows
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]              python3.10
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]         源文件运行
 - 代码版本:[比如0.5.0,1.0.0]                                                           2022年8月30日的版本

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by NRSMDLFSF** [comment]
我今天试了 也是这个问题![IMG_20220912_003226.jpg](https://user-images.githubusercontent.com/94678725/189538757-8303c0f1-9bae-47fc-8190-4c87143aef42.jpg)

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
