### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 961440300** [Samueli924/chaoxing#143]
![fghjk](https://user-images.githubusercontent.com/112849645/188382854-236a5f28-0ad6-4381-b34b-141ab95f9916.png)

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
