### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by xxxxxy211** [Samueli924/chaoxing#144]
**形容Bug的信息**

当前视频：02-part1.mp4
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：/app/main.py
错误行数：186
错误原因:Expecting value: line 1 column 1 (char 0)
请截图提交至Github或Telegram供作者修改代码

**Screenshots**
![image](https://user-images.githubusercontent.com/59924364/188399404-4f32921d-4422-4f49-957b-2c0e765b7619.png)
**运行环境 (请完善以下信息):**
 - 系统：Windows 11 专业版 21H2 22000.856
 - Python环境版本:docker
 - 运行方式: docker
 - 代码版本:当前最新版本，git clone --depth=1 https://github.com/Samueli924/chaoxing获取，版本未知

**Comment by cyear** [comment]
最新源码已修复，等待合并

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
