### ISSUE TITLE
[Advice]

### ISSUE THREAD

**Issue by CcNep** [Samueli924/chaoxing#145]
**清晰有逻辑的提出问题**
详细内容
   <dd>【9011】很抱歉，您没有权限访问这个页面！code=6 </dd>
    </dl>
    <div class="infoCon">
        <p>198846465</p>
        <p>27.226.73.88</p>
        <p>mooc-462402635-4gtpt</p>
        <p>2022-09-05 21:29:56</p>
    </div>
</div>
</body>
</html>
: 0
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
