### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by yyyyyztong** [Samueli924/chaoxing#148]
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：C:\Users\86136\Downloads\chaoxing-2.4.2\main.py
错误行数：186
错误原因:[Errno Expecting value] <!doctype html>

.................................................................

        <dd>【9011】很抱歉，您没有权限访问这个页面！code=6 </dd>
    </dl>
    <div class="infoCon">
        <p>170583192</p>
        <p>120.229.41.77</p>
        <p>mooc-1233826885-f6ffx</p>
        <p>2022-09-15 03:20:41</p>
    </div>
</div>
</body>
</html>
: 0

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
