### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Yangyang0vo** [Samueli924/chaoxing#152]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
186 行 
当前视频：1.flv
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：/Users/yangyang/Downloads/chaoxing/main.py
错误行数：186
错误原因:Expecting value: line 1 column 1 (char 0)
**Screenshots**
插入程序出现BUG的截图
<img width="542" alt="image" src="https://user-images.githubusercontent.com/85276107/190917785-4b717dc5-7749-4691-b900-a03e4bf21056.png">

**运行环境 (请完善以下信息):**
 - 系统：macOS13.0(22A5342f)
 - Python环境版本:Python3.11
 - 运行方式: 源代码运行
 - 代码版本:2.42

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by cyear** [comment]
git clone https://github.com/cyear/chaoxing.git
这个，目前暂时修复，这个问题还是有，最近几天再看看

**Comment by ygwbl** [comment]
我也有这也的问题了
![屏幕截图 2022-09-19 111503](https://user-images.githubusercontent.com/99161400/190944287-48493e83-2883-4406-9d31-6c7c4eaf6765.png)

**Comment by Yangyang0vo** [comment]
> 我也有这也的问题了 ![屏幕截图 2022-09-19 111503](https://user-images.githubusercontent.com/99161400/190944287-48493e83-2883-4406-9d31-6c7c4eaf6765.png)
用楼上的 我已解决

**Comment by Yangyang0vo** [comment]
> git clone https://github.com/cyear/chaoxing.git 这个，目前暂时修复，这个问题还是有的，最近再看看

谢谢
