### ISSUE TITLE
[Feature Request]
我在git push时，提示无权限，不能合并代码

### ISSUE THREAD

**Issue by cyear** [Samueli924/chaoxing#153]
**这个功能建议是否与使用过程中出现的BUG有关**
详细的描述

**描述你想添加的功能**
详细的描述

**补充内容**
可以上传截图或文字表达补充建议

**Comment by cyear** [comment]
我是新接触到git push，这个问题经过百度和谷歌暂未得到解决😂

**Comment by InEase** [comment]
push到源仓库肯定是没有权限的，要是能push上来那岂不是开源代码很容易被破坏嘛

正确的流程应该是先Fork，然后Push到Fork的仓库，然后从Fork的仓库PR到源仓库

**Comment by cyear** [comment]
> push到源仓库肯定是没有权限的，要是能push上来那岂不是开源代码很容易被破坏嘛
> 
> 正确的流程应该是先Fork，然后Push到Fork的仓库，然后从Fork的仓库PR到源仓库

可以具体说说吗
