### ISSUE TITLE
登录后刷课无权限

### ISSUE THREAD

**Issue by qwe8511066** [Samueli924/chaoxing#154]
无权限
![QQ截图20220919174054](https://user-images.githubusercontent.com/23131741/190991079-7c562c8f-9b2e-4f79-bb2e-86778f487e29.png)

**Comment by cyear** [comment]
最新已修复，暂未合并

**Comment by qwe8511066** [comment]
效率！等你合并吧

**Comment by suyunze** [comment]
![微信截图_20220920165915](https://user-images.githubusercontent.com/45612474/191216031-3ce201a7-92a1-463e-a7ae-018780742719.png)
![微信截图_20220920165929](https://user-images.githubusercontent.com/45612474/191216063-52e52b9a-6452-419c-8563-fc9c03ba37ed.png)
waiting...

**Comment by cyear** [comment]
> 无权限 ![QQ截图20220919174054](https://user-images.githubusercontent.com/23131741/190991079-7c562c8f-9b2e-4f79-bb2e-86778f487e29.png)

https://github.com/cyear/chaoxing.git 请前往此处下载windows测试 文件名为：
cyear_chaoxing0.1.2209.1.zip

**Comment by cyear** [comment]
> ![微信截图_20220920165915](https://user-images.githubusercontent.com/45612474/191216031-3ce201a7-92a1-463e-a7ae-018780742719.png) ![微信截图_20220920165929](https://user-images.githubusercontent.com/45612474/191216063-52e52b9a-6452-419c-8563-fc9c03ba37ed.png) waiting...

https://github.com/cyear/chaoxing.git 请前往此处下载windows测试 文件名为：
cyear_chaoxing0.1.2209.1.zip

**Comment by qwe8511066** [comment]
已用一个上午 目前稳定

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
