### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by sxceocom** [Samueli924/chaoxing#156]
**形容Bug的信息**
出现报错<class 'AttributeError'>
错误文件名：/root/chaoxing/main.py
错误行数：235
错误原因:'NoneType' object has no attribute 'get'

**Screenshots**
![6WHYML613HTQ$X 3JOT0E37](https://user-images.githubusercontent.com/86223309/191527103-31468a72-80ff-416c-961b-b91459360c3f.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:Python3.9
 - 运行方式: 源代码运行
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
