### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by tong-ting** [Samueli924/chaoxing#157]
![image](https://user-images.githubusercontent.com/62937343/191946919-f8744c46-ba26-4029-ba59-6207439fde92.png)

**Comment by linchchi** [comment]
https://github.com/cyear/chaoxing有人解决了

**Comment by tong-ting** [comment]
很抱歉，网址404


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Samueli924/chaoxing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Samueli924/chaoxing] [BUG反馈] (Issue #157)





 
https://github.com/cyear/chaoxing有人解决了

**Comment by Samueli924** [comment]
已由[a81608882](https://github.com/a81608882)于[PR #142](https://github.com/Samueli924/chaoxing/pull/142)中修复。
请尝试重新拉取代码后使用，谢谢
