### ISSUE TITLE
运行错误[BUG反馈]

### ISSUE THREAD

**Issue by sunnangua** [Samueli924/chaoxing#159]
![屏幕截图 2022-09-26 153633](https://user-images.githubusercontent.com/93716440/192220404-b378e338-57dc-4646-a6d1-3cbc96c99901.png)
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 768792587** [comment]
![HAY PZX~_Q4K46%40C2~(63](https://user-images.githubusercontent.com/114583730/192772439-f69aef9e-5b94-4bfa-ae19-0cb46c47c2a7.png)
有bug，是视频任务

**Comment by sunnangua** [comment]
有没有解决办法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月28日(周三) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Samueli924/chaoxing] 运行错误[BUG反馈] (Issue #159)




 

 有bug，是视频任务
