### ISSUE TITLE
该项目的解析方法

### ISSUE THREAD

**Issue by AlwaysLazy21** [Samueli924/chaoxing#160]
# 本项目采用什么方法获取进行http请求时的参数。

## 疑问

我在写关于学习通项目的时候，有些http的表单参数整合到html中了，需要解析html，才能获取对应的参数信息，但是我在浏览该项目的时候，并没有发现我熟悉的解析方法，所以该项目是怎么获取所需的请求参数的呢？我是个刚写过一两个小项目的小白，有些东西可能有些不太清楚，望大佬指教一下。

**Comment by Samueli924** [comment]
使用的Beautifulsoup4库，这是他的[文档](https://beautiful-soup-4.readthedocs.io/en/latest/)
