### ISSUE TITLE
[Feature Request]可以在手机termux运行吗？

### ISSUE THREAD

**Issue by WangHuimin520** [Samueli924/chaoxing#162]
可以适配一下再手机termux上使用吗？手机使用可能比电脑方便

**Comment by cyear** [comment]
> 可以适配一下再手机termux上使用吗？手机使用可能比电脑方便

更改其中一个库后可以使用

**Comment by cyear** [comment]
> **apt install python
> git clone https://github.com/Samueli924/chaoxing.git
> cd chaoxing-main
> pip install -r requirements.txt
> python main.py
> 别忘了给termux做保活**

用于密码隐藏的库pip会报错，建议去掉

**Comment by cyear** [comment]
> > > **apt install python
> > > git clone https://github.com/Samueli924/chaoxing.git
> > > cd chaoxing-main
> > > pip install -r requirements.txt
> > > python main.py
> > > 别忘了给termux做保活**
> > 
> > 用于密码隐藏的库pip会报错，建议去掉
> 
> **报错也没事 能直接跑**

不能跑

**Comment by WangHuimin520** [comment]
感谢兄弟啊，之前我也研究过，也是有个库报错，然后就放弃了

**Comment by WangHuimin520** [comment]
你现在实际可以用了吗😊

**Comment by cyear** [comment]
> > > > > **apt install python
> > > > > git clone https://github.com/Samueli924/chaoxing.git
> > > > > cd chaoxing-main
> > > > > pip install -r requirements.txt
> > > > > python main.py
> > > > > 别忘了给termux做保活**
> > > > 
> > > > 用于密码隐藏的库pip会报错，建议去掉
> > > 
> > > **报错也没事 能直接跑**
> > 
> > 不能跑
> 
> 
> apt install python
> apt install git
> //安装maskpass
> git clone https://github.com/FuturisticGoo/maskpass.git
> cd maskpass
> python setup.py install
> cd 
> //
> git clone https://github.com/Samueli924/chaoxing.git
> cd chaoxing-main
> pip install -r requirements.txt
> python main.py
> 
> 你试试
> 报错是因为https://github.com/Samueli924/chaoxing/issues/161 其他正常的
> 
> ![IMG_20221023_171044.jpg](https://user-images.githubusercontent.com/64531014/197384417-a39ccfa9-7a55-4917-b37b-d59d7f2ea1d8.jpg)

麻烦，不如重构，现在反馈问题挺多

**Comment by WangHuimin520** [comment]
好的感谢兄弟
