### ISSUE TITLE
[BUG反馈]出现报错<class 'requests.exceptions.JSONDecodeError'>

### ISSUE THREAD

**Issue by 122868** [Samueli924/chaoxing#164]
开始读取标签信息

当前章节：1.1:何为心理健康

当前视频：1.1 何为心理健康.mp4
当前视频任务已完成
当前任务： 1.1 何为心理健康.mp4 已完成                                                                            
开始读取标签信息

当前章节：1.1:何为心理健康
跳过非视频任务
开始读取标签信息

当前章节：1.2:心理健康的状况

当前视频：1.2 心理健康的状况.mp4
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：D:\Project\Pycharm\chaoxing-2.4.2\main.py
错误行数：186
错误原因:Expecting value: line 1 column 1 (char 0)
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Comment by 122868** [comment]
使用的是pycharm 2022.2版本，python3.9

**Comment by UPman24** [comment]
我也遇到了个别课程是这样的<class 'requests.exceptions.JSONDecodeError'>

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
