### ISSUE TITLE
报错<class 'requests.exceptions.ConnectionError'>

### ISSUE THREAD

**Issue by 1035406941** [Samueli924/chaoxing#166]
**形容Bug的信息**
错误文件名：C:\Users\10354\chaoxing\main.py
错误行数：186
错误原因:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Screenshots**
、

**运行环境 (请完善以下信息):**
![`KQ8 ~%UEJT5GR3JVWNDFOL](https://user-images.githubusercontent.com/84302732/195097724-2ff7c886-83d7-493b-80bc-aab80428b12c.png)
![`KQ8 ~%UEJT5GR3JVWNDFOL](https://user-images.githubusercontent.com/84302732/195097899-4a26d16a-dcb9-4d08-a664-7d1e99ad5f14.png)

 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by hdy111** [comment]
![IMG_20221013_080446](https://user-images.githubusercontent.com/83997017/195473901-98d3c823-a38b-4501-9f5d-97d831d1cf14.jpg)
我也是出现这种问题

**Comment by Samueli924** [comment]
> **形容Bug的信息** 错误文件名：C:\Users\10354\chaoxing\main.py 错误行数：186 错误原因:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 请截图提交至Github或Telegram供作者修改代码 点击回车键退出程序
> 
> **Screenshots** 、
> 
> **运行环境 (请完善以下信息):** ![KQ8 ~%UEJT5GR3JVWNDFOL](https://user-images.githubusercontent.com/84302732/195097724-2ff7c886-83d7-493b-80bc-aab80428b12c.png) ![KQ8 ~%UEJT5GR3JVWNDFOL](https://user-images.githubusercontent.com/84302732/195097899-4a26d16a-dcb9-4d08-a664-7d1e99ad5f14.png)
> 
> * 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
> * Python环境版本:[比如:Python2,Python3.6,Python3.8]
> * 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
> * 代码版本:[比如0.5.0,1.0.0]
> 
> **其他内容** 您觉得对问题反馈有帮助的内容

你这个需要检查一下你这边的网络情况，可能是网络不稳定或代理有问题。
