### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 2323602928** [Samueli924/chaoxing#167]
**形容Bug的信息**
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：C:\Users\2323602928\Desktop\chaoxing-main\main.py
错误行数：185
错误原因:Expecting value: line 1 column 1 (char 0)

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/103060167/195132758-e6707216-c78d-4e5e-8815-13040b030419.png)

**运行环境 (请完善以下信息):**
 - 系统：[Windows10]
 - Python环境版本:[Python3.9]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
