### ISSUE TITLE
[Advice]账号密码正确提示错误

### ISSUE THREAD

**Issue by FC114514** [Samueli924/chaoxing#169]
**清晰有逻辑的提出问题**
详细内容

**Comment by joshefi** [comment]
同遇到此问题我使用python3.10.6于win10平台正常运行密码无误，我直接复制到centos7上使用python3.9..10就出了问题显示账号密码不对，重新下载程序输入密码，centos平台仍有误

**Comment by cyear** [comment]
> 同遇到此问题我使用python3.10.6于win10平台正常运行密码无误，我直接复制到centos7上使用python3.9..10就出了问题显示账号密码不对，重新下载程序输入密码，centos平台仍有误

请提供详细错误截图以便修复

**Comment by ShiroSekai** [comment]
我也遇到了同样的问题，可否考虑支持直接填入Cookie？

**Comment by cyear** [comment]
> 我也遇到了同样的问题，可否考虑支持直接填入Cookie？

请提供具体截图

**Comment by Laeoo** [comment]
2022-10-17 00:16:57,049 - main - INFO - 登陆中
2022-10-17 00:16:57,050 - ChaoxingAPI - DEBUG - 发送登录数据
2022-10-17 00:16:57,225 - ChaoxingAPI - DEBUG - 收到返回数据
2022-10-17 00:16:57,226 - ChaoxingAPI - ERROR - 登录失败：{'msg2': '用户名或密码错误', 'status': False}
任务已结束，请点击回车键退出程序

**Comment by cyear** [comment]
> 2022-10-17 00:16:57,049 - main - INFO - 登陆中
> 2022-10-17 00:16:57,050 - ChaoxingAPI - DEBUG - 发送登录数据
> 2022-10-17 00:16:57,225 - ChaoxingAPI - DEBUG - 收到返回数据
> 2022-10-17 00:16:57,226 - ChaoxingAPI - ERROR - 登录失败：{'msg2': '用户名或密码错误', 'status': False}
> 任务已结束，请点击回车键退出程序
> 
> 
> 
> Python 3.10.8

密码中是否含有中文字符，例如。，？！

**Comment by Laeoo** [comment]
没有，纯英文加数字

**Comment by Laeoo** [comment]
> > 2022-10-17 00:16:57,049 - main - INFO - 登陆中
> > 2022-10-17 00:16:57,050 - ChaoxingAPI - DEBUG - 发送登录数据
> > 2022-10-17 00:16:57,225 - ChaoxingAPI - DEBUG - 收到返回数据
> > 2022-10-17 00:16:57,226 - ChaoxingAPI - ERROR - 登录失败：{'msg2': '用户名或密码错误', 'status': False}
> > 任务已结束，请点击回车键退出程序
> > Python 3.10.8
> 
> 密码中是否含有中文字符，例如。，？！

不好意思，发现是密码被改了

**Comment by cyear** [comment]
> > > 2022-10-17 00:16:57,049 - main - INFO - 登陆中
> > > 2022-10-17 00:16:57,050 - ChaoxingAPI - DEBUG - 发送登录数据
> > > 2022-10-17 00:16:57,225 - ChaoxingAPI - DEBUG - 收到返回数据
> > > 2022-10-17 00:16:57,226 - ChaoxingAPI - ERROR - 登录失败：{'msg2': '用户名或密码错误', 'status': False}
> > > 任务已结束，请点击回车键退出程序
> > > Python 3.10.8
> > 
> > 密码中是否含有中文字符，例如。，？！
> 
> 不好意思，发现是密码被改了

已解决请关闭这个议题
