### ISSUE TITLE
只能刷视频任务点嘛，能不能支持阅读，图片等任务点

### ISSUE THREAD

**Issue by HankMo** [Samueli924/chaoxing#170]
只能刷视频任务点嘛，能不能支持阅读，图片，音频等任务点

**Comment by cyear** [comment]
> 只能刷视频任务点嘛，能不能支持阅读，图片，音频等任务点

由于账号有限，未遇见更多任务点

**Comment by yhm97** [comment]
我碰见音频任务了，添加了支持。
阅读，图片的任务稍微修改下应该也可以，但我没有相关的任务，不确定请求url是啥样的
