### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by linbabi** [Samueli924/chaoxing#173]
出现报错<class 'IndexError'>
错误行数：154
错误原因:list index out of range
请截图提交至Github或Telegram供作者修改代码

**Comment by cyear** [comment]
> 出现报错<class 'IndexError'>
> 错误行数：154
> 错误原因:list index out of range
> 请截图提交至Github或Telegram供作者修改代码

请提供具体截图，以及输入内容

**Comment by linbabi** [comment]
[](url)
![}S5 C`ZO8@D(W9FM6 GQY9V](https://user-images.githubusercontent.com/88957448/196413886-e683919d-dee0-44d9-bd9e-2b63ddf76fad.png)

**Comment by linbabi** [comment]
![L@D}7OW$8D%)54OXKS9P}HD](https://user-images.githubusercontent.com/88957448/196415360-610ab786-b042-442d-8d99-9bbad0913df4.png)
