### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by camellia19** [Samueli924/chaoxing#174]
**形容Bug的信息**
<class 'KeyError'>

**运行环境 (请完善以下信息):**
 - 系统: windows10 21h1
 - Python环境版本: python 3.7
 - 运行方式: 可执行文件exe运行
 - 代码版本:2.4.2

**Comment by cyear** [comment]
> **形容Bug的信息**
> <class 'KeyError'>
> 
> **运行环境 (请完善以下信息):**
>  - 系统: windows10 21h1
>  - Python环境版本: python 3.7
>  - 运行方式: 可执行文件exe运行
>  - 代码版本:2.4.2
> 
> 
> 

更换到源码运行
