### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by zhangyutong0917** [Samueli924/chaoxing#180]
请输入密码(已自动隐藏)出现报错<class 'termios.error'>
错误文件名：/Users/shenming/chaoxing/main.py
错误行数：145
错误原因:(25, 'Inappropriate ioctl for device')
请截图提交至Github或Telegram供作者修改代码
![IMG_20221024_082436](https://user-images.githubusercontent.com/113247353/197425966-6234b781-addb-4edd-b052-7feea3d50846.png)

**Comment by Samueli924** [comment]
不要在Pycharm里面直接运行，
请在终端运行
