### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by qylife** [Samueli924/chaoxing#181]
**形容Bug的信息**
所有的视频都直接跳过了，

**Screenshots**
![image](https://user-images.githubusercontent.com/116621410/197690685-18716aa8-6ab4-456c-82ac-937e3bc22bda.png)

**运行环境 (请完善以下信息):**
使用 docker compose 运行

**其他内容**

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
