### ISSUE TITLE
[Advice] 您好，请问web版目前是不再更新吗

### ISSUE THREAD

**Issue by 2563411574** [Samueli924/chaoxing#182]
**清晰有逻辑的提出问题**
详细内容
您好，请问web版目前是不再更新吗？
是否考虑前后端分离呢

**Comment by Samueli924** [comment]
目前没有更新的计划哈

**Comment by qylife** [comment]
请问有开发者可以一起讨论的地方吗？

**Comment by Samueli924** [comment]
> 请问有开发者可以一起讨论的地方吗？

我刚开放了discussion，可以在这个库的discussions里进行讨论的哈
