### ISSUE TITLE
[BUG反馈]获取任务状态时403,代码为HEAD版本

### ISSUE THREAD

**Issue by GiTHubKi** [Samueli924/chaoxing#183]
**形容Bug的信息**
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：C:\Users\Administrator\Desktop\chaoxing\main.py
错误行数：190
错误原因:Expecting value: line 1 column 1 (char 0)

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/26586433/198168112-0c9ff559-d16c-49b9-8c59-30e1858ee8c9.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows Server2016
 - Python环境版本:Python3.11
 - 运行方式: 源代码运行
 - 代码版本:[6aa2b79](https://github.com/Samueli924/chaoxing/commit/6aa2b791d42fe3d520641ba66ea369e7dccf4504)

**其他内容**
获取视频信息时异常

**Comment by GiTHubKi** [comment]
接口返回403导致的json解析异常,请问这种情况怎么处理
![image](https://user-images.githubusercontent.com/26586433/198180087-fcae9ee0-4c3b-4b05-a1fe-8339afe5b2cc.png)

**Comment by yhm97** [comment]
音频任务导致的，我也碰见了，尝试修复了下。拉新代码试试呢

**Comment by GiTHubKi** [comment]
> 

已测试目前正常,多谢哥们
