### ISSUE TITLE
[BUG反馈]<class 'requests.exceptions.SSLError'>

### ISSUE THREAD

**Issue by SanThousand** [Samueli924/chaoxing#184]
出现报错<class 'requests.exceptions.SSLError'>
错误文件名：/home/chaoxing-main/main.py
错误行数：153
错误原因:HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
请截图提交至Github或Telegram供作者修改代码
![image](https://user-images.githubusercontent.com/82409723/198175856-8653ba2f-65c3-4d2a-b9eb-3d3c99d37320.png)
系统：Centos7.6
Python环境版本: Python 3.10.7
运行方式: 源代码运行

**Comment by Samueli924** [comment]
https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module
