### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by helloswxy** [Samueli924/chaoxing#189]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
<img width="665" alt="截屏2022-11-01 09 46 32" src="https://user-images.githubusercontent.com/105974758/199154516-88baa713-2717-439c-b0a8-99f276d100b5.png">

**运行环境 (请完善以下信息):**
 - 系统：Windows2012
 - Python环境版本:python3.10.4
 - 运行方式: 源代码运行
 - 代码版本:

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
