### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 54736424364gaoze** [Samueli924/chaoxing#191]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]
![image](https://user-images.githubusercontent.com/93146422/199189422-826d12b6-e8cb-4d8a-a787-bb3cfd813dcb.png)

![44CHX~1SBE45U}D}1`4CE~H](https://user-images.githubusercontent.com/93146422/199189702-28a01007-5612-479f-bfe7-763863bb1a70.png)

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
