### ISSUE TITLE
[BUG反馈] 出现报错<class 'requests.exceptions.ReadTimeout'>

### ISSUE THREAD

**Issue by wyl2003** [Samueli924/chaoxing#192]
**形容Bug的信息**
当前章节：3.1.1.5:lecture05

当前视频：Lab01_task1_MainProgram.mp4
当前播放速率：2倍速
当前任务： Lab01_task1_MainProgram.mp4 |#####################                   | 53%  6min 44s/12min 34s     出现报错<class 'requests.exceptions.ReadTimeout'>
错误文件名：/root/chaoxing/main.py
错误行数：195
错误原因:HTTPSConnectionPool(host='mooc1-api.chaoxing.com', port=443): Read timed out. (read timeout=None)
请截图提交至Github或Telegram供作者修改代码

**Screenshots**
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/108109393/199434042-c3fad17d-a2a6-4cda-b8b9-3ab8ded62ef6.png">

**运行环境 (请完善以下信息):**
 - 系统：Armbian 22.08.8 Bullseye with Linux 5.15.74-sunxi
 - Python环境版本: python3.9.2
 - 运行方式: 源代码运行
 - 代码版本: 2.4.2

**Comment by wyl2003** [comment]
猜测是网络问题，某次请求没有响应导致报错，也许可以在响应超时后再次请求。

**Comment by Samueli924** [comment]
请拉取最新版本后重试，谢谢。
