### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 54736424364gaoze** [Samueli924/chaoxing#196]
![image](https://user-images.githubusercontent.com/93146422/199953082-325a3bad-94e2-4bd2-b186-9782f8abaf92.png)

**Comment by LeeYoung618** [comment]
请问解决了吗，我也是这个问题

**Comment by 54736424364gaoze** [comment]
这是我跑在云上的，自己电脑的话py3.9版本就可以了，下载好配置文件。不过现在貌似不行了，应该是修复官方bug了

**Comment by LeeYoung618** [comment]
我也是在云上跑不了，在本地就可以。云上报错和你的一样

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
