### ISSUE TITLE
希望大佬新增无人看守功能

### ISSUE THREAD

**Issue by mayjack0312** [Samueli924/chaoxing#199]
**这个功能建议是否与使用过程中出现的BUG有关**
使用过程中偶尔会出现报错，暂不清楚相关原因
可能会和无人看守操作起部分冲突

**描述你想添加的功能**
每次运行脚本都要根据提示选数字
能否增加类似bat文件的批处理脚本
实现配置完脚本然后双击&运行后就可以完全不用管他了

**补充内容**
无

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
