### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by camellia19** [Samueli924/chaoxing#202]
只读取标题 不观看视频 直接全部跳过

可执行exe文件

**Comment by cyear** [comment]
https://github.com/cyear/chaoxing/releases/tag/v0.1.22.1118.Beta 已修复

**Comment by camellia19** [comment]
> https://github.com/cyear/chaoxing/releases/tag/v0.1.22.1118.Beta 已修复

还是有部分账号只读取标题

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
