### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by mayjack0312** [Samueli924/chaoxing#204]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
```
- main - INFO - 开始获取所有章节
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
开始读取标签信息
任务已结束，请点击回车键退出程序
```

**运行环境**
 - 系统:Windows10 22H2 19045.2251
 - Python环境版本:3.10.1
 - 运行方式:源代码运行
 - 代码版本:2.4.2

**其他内容**
无

**Comment by 54736424364gaoze** [comment]
我也是的

**Comment by mayjack0312** [comment]
> 我也是的

等等看吧，看看大佬还有啥补救法子
感觉估计是接口挂了

**Comment by cyear** [comment]
https://github.com/cyear/chaoxing/releases/tag/v0.1.22.1118.Beta 已修复

**Comment by mayjack0312** [comment]
> https://github.com/cyear/chaoxing/releases/tag/v0.1.22.1118.Beta 已修复

6了6了

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
