### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by cpkkcb** [Samueli924/chaoxing#208]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
![image](https://user-images.githubusercontent.com/31617622/203569015-3472db91-b717-4a4b-8cdb-133e4514b762.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows]
 - Python环境版本:[Python3.3.7]
 - 运行方式: python main.py
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已修复，请拉取最新代码后重试
