### ISSUE TITLE
[Feature Request]希望增加配置文件启动方式

### ISSUE THREAD

**Issue by cclucky1** [Samueli924/chaoxing#209]
**这个功能建议是否与使用过程中出现的BUG有关**
五

**描述你想添加的功能**
我想使用群晖NAS24小时后台运行，现有的运行方式在退出终端后无法正常运行，能否增加配置文件启动方式通过nohup放入后台运行

**补充内容**

**Comment by mslxl** [comment]
不妨尝试一下 screen 或者 tmux 等终端复用工具?

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
