### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by ZhangXG-NJU** [Samueli924/chaoxing#214]
2022-12-29 19:00:54,478 - main - INFO - 登陆中
出现报错<class 'requests.exceptions.SSLError'>
错误文件名：C:\Users\Administrator\Downloads\chaoxing-main\MAIN.PY
错误行数：158
错误原因:HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Comment by Samueli924** [comment]
https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module
