### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Aescn** [Samueli924/chaoxing#218]
![image](https://user-images.githubusercontent.com/85007494/220150780-5a7ad068-d897-4ae5-87ff-4d890bd4f8e5.png)

**Comment by Aescn** [comment]
应该是我按什么了

**Comment by Samueli924** [comment]
这个是你的代理问题哈，你可以检查一下你的代理情况后重试

**Comment by Aescn** [comment]
> 



> 这个是你的代理问题哈，你可以检查一下你的代理情况后重试

ok，谢谢
