### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by wanbduj2869** [Samueli924/chaoxing#219]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![Snipaste_2023-02-25_19-08-18](https://user-images.githubusercontent.com/120785706/221353590-3313442b-6cfe-40c5-a792-a2c9318d7c2b.jpg)

**运行环境 (请完善以下信息):**
 - 系统：[Linux(Anolis OS)]
 - Python环境版本:[Python3.10.10]
 - 运行方式: 源代码运行
 - 代码版本:[2.4.3]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by lliioollcn** [comment]
等一等，换个网，你密码错的次数太多了

**Comment by wanbduj2869** [comment]
谢谢回复 但是我刚刚重新试过 我确定密码是正确的 好像还是不行 @lliioollcn

**Comment by lliioollcn** [comment]
python版本低一点试试，刚刚看差了，这是重定向次数过多

**Comment by wanbduj2869** [comment]
我用python3.9试了一下 还是不行欸

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
