### ISSUE TITLE
[Feature Request]有没有可能做成多线程的形式

### ISSUE THREAD

**Issue by EvATive7** [Samueli924/chaoxing#221]
**这个功能建议是否与使用过程中出现的BUG有关**
否

**描述你想添加的功能**
大佬有没有考虑把程序改成多线程的形式播放视频，达到同时可以刷多个视频的效果ヾ(•ω•`)o

**补充内容**
或者，大佬有什么顾虑吗？学习通是否支持，或者风控相关？

**Comment by DaXue403** [comment]
同时刷多个视频大概率会被风控发现，还是省省吧
