### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by asdukw** [Samueli924/chaoxing#222]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
如图
**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/113411984/223985290-2c19e160-d6b1-498b-ba64-b38a86ab8a0b.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - 版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2023/‎3/‎9
操作系统版本	22000.1574
体验	Windows 功能体验包 1000.22000.1574.0

 - Python环境版本:[比如:Python2,Python3.6,Python3.8]python3.11
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]源代码运行
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by lliioollcn** [comment]
换个网，别开代理
