### ISSUE TITLE
[BUG反馈] 部分视频课程无法完成

### ISSUE THREAD

**Issue by lliioollcn** [Samueli924/chaoxing#223]
**形容Bug的信息**
某个视频播放时，在显示当前"播放速率：1倍速"后报错
内容显示无权限访问url

**Screenshots**
![图片](https://user-images.githubusercontent.com/44719954/223985244-9e47bbdc-0a9b-4723-848e-474faeaf203f.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows 10 专业版22H2 19045.2604
 - Python环境版本: Python 3.9.10
 - 运行方式: 源代码运行
 - 代码版本: [f5db7f5316c997e807bf6694bf6ad192f50697e1](https://github.com/Samueli924/chaoxing/tree/f5db7f5316c997e807bf6694bf6ad192f50697e1)

**其他内容**

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
