### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by taciturn-eyes** [Samueli924/chaoxing#224]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
错误行数：195
错误原因:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/77370454/224035864-4e7367ea-2db3-4628-9563-8097f6bea453.png)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:Python3.8
 - 运行方式: 可执行文件exe运行
 - 代码版本:2.4.3

**其他内容**
程序跑着报错了，反馈一下给大大参考

**Comment by lliioollcn** [comment]
链接断开了，你换个网

**Comment by xia0ne** [comment]
貌似加了验证

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
