### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by KayQuinn** [Samueli924/chaoxing#225]
错误行数：165
错误原因：'result'
<img width="520" alt="屏幕截图 2023-03-14 175207" src="https://user-images.githubusercontent.com/111349351/224963174-316a571b-e65b-495e-8e75-b27cf61da8d9.png">

 - 系统：win11 22h2
 - Python环境版本:python3.11
 - 运行方式:源代码运行
 - 代码版本:2.4.3

程序报错了，请大佬参考

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
