### ISSUE TITLE
[BUG反馈]连接错误

### ISSUE THREAD

**Issue by zkzk666** [Samueli924/chaoxing#226]
2023-03-19 21:53:03,472 - main - INFO - 登陆中
出现报错<class 'requests.exceptions.ProxyError'>
错误文件名：main.py
错误行数：158
错误原因:HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ff1005040>: Failed to establish a new connection: [Errno 111] Connection refused')))
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

这是啥情况

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢

**Comment by zkzk666** [comment]
邮件已收到。
