### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Carl-zqw** [Samueli924/chaoxing#227]
**形容Bug的信息**
在运行中出现，一直重复输出当前任务
错误原因:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Screenshots**
插入程序出现BUG的截图
![c209d662a2892a0312f31121e0b835c](https://user-images.githubusercontent.com/63358460/226503879-b9abf167-0c95-4607-9ff0-76b4debc2967.png)

**运行环境 (请完善以下信息):**
 - 系统：[window10 专业工作站版(10.0.19045 内部版本 19045)]
 - Python环境版本:[Python3.9.13]
 - 运行方式: [源代码运行，anaconda prompt]
 - 代码版本:[2.3.1]

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
