### ISSUE TITLE
[BUG反馈]connection aborted

### ISSUE THREAD

**Issue by vannnnav** [Samueli924/chaoxing#228]
**形容Bug的信息**
195

**Screenshots*

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

[**其他内容**](url)
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
