### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by henghenghh** [Samueli924/chaoxing#229]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/100331399/227104258-9e3d496e-f27f-4e5c-89c6-6c01b6c5e72c.png">

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
