### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by StudyingLover** [Samueli924/chaoxing#230]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/68844494/227668668-33d5baa9-0907-44b9-991a-00e2ca4ee106.png)

**运行环境 (请完善以下信息):**
 - 系统：Linux raspberrypi 6.1.19-v8+
 - Python环境版本:python 3.9.2
 - 运行方式: 源代码运行
 - 代码版本:latest

**其他内容**
只在部分情况出现

**Comment by Samueli924** [comment]
这个是代理报错的，你可以检查一下你的代理设置有没有问题，或者关闭代理尝试一下
