### ISSUE TITLE
[BUG反馈] 无法自动观看下一节

### ISSUE THREAD

**Issue by Miaoerr** [Samueli924/chaoxing#235]
**形容Bug的信息**
日志：
2023-04-08 14:29:56,140 - main - WARNING - 章节数据错误,可能是课程存在验证码,正在尝试重新登录
开始读取标签信息
任务已结束，请点击回车键退出程序
描述：
账号下的每门课程都不能自动播放下一节，只能自行到课程中答题之后才可以用本程序进行下一节的观看

**Screenshots**
![image](https://user-images.githubusercontent.com/49992926/230710094-9f7d8a42-a07f-4b1e-b1c6-4f60cfcc7a6f.png)

**运行环境 (请完善以下信息):**
 - 系统：Linux Debian 11 Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
 - Python环境版本: Python 3.9.2
 - 运行方式: 源代码运行
 - 代码版本: 2.4.4

**其他内容**
是账号问题吗？还是课程和普通课程不一样

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
