### ISSUE TITLE
[BUG反馈]云服务器上运行报错

### ISSUE THREAD

**Issue by Rayscan321** [Samueli924/chaoxing#240]
**形容Bug的信息**
BUG出现行数：158

**Screenshots**
![image](https://user-images.githubusercontent.com/106383944/233702563-cb7bc502-803f-4827-99ec-5ea3f9870aec.png)

**运行环境 (请完善以下信息):**
 - 系统：centos7.9
 - Python环境版本:Python3.9.7
 - 运行方式: 源代码运行
 - 代码版本:

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by buchiLZ** [comment]
你没有安装ssl模块或者ssl版本太低,尝试更新一下

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
