### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by coderxiaoxin** [Samueli924/chaoxing#242]
**形容Bug的信息**
main.py
错误行数：195
错误原因:HTTPSConnectionPool(host='mooc1-api.chaoxing.com', port=443): Max retries exceeded with url: /multimedia/log/a/250251269/bbd4f60733e5d74ca360fb017e595338?otherInfo=nodeId_572658302-cpi_250251269-rt_0.9-ds_1-ff_1-be_0_0-vt_1-v_6-enc_890592ea6240220a94fc7d9115c4e5dd&courseId=225567608&playingTime=290&duration=360&jobid=1606434322865523&clipTime=0_360&clazzId=72163985&objectId=2bc013f1815ccccb8d4a43920bc6c747&userid=228368107&isdrag=0&enc=e26ea167b0f1aaf6c2b9736a6eacadf7&rt=0.9&dtype=Video&view=pc&_t=1682391413640 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
**Screenshots**
插入程序出现BUG的截图
<img width="570" alt="image" src="https://user-images.githubusercontent.com/19337278/234163909-2f51c062-33ad-4710-a6e6-ad9bc2cadf69.png">

**运行环境 (请完善以下信息):**
 - 系统：macOS
 - Python环境版本:Python3.9.13
 - 运行方式: 源代码运行
 - 代码版本:2.4.4

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
