### ISSUE TITLE
[BUG反馈]HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by SSLError(SSLError('No cipher can be selected.')))

### ISSUE THREAD

**Issue by buchiLZ** [Samueli924/chaoxing#243]
**形容Bug的信息**
2023-05-02 15:38:22,516 - main - INFO - 正在读取本地用户数据...
请输入手机号17853296179
请输入密码(已自动隐藏)############
2023-05-02 15:38:34,204 - main - INFO - 登陆中
出现报错<class 'requests.exceptions.SSLError'>
错误文件名：/home/buchi/Script/chaoxing/main.py
错误行数：157
错误原因:HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by SSLError(SSLError('No cipher can be selected.')))
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Screenshots**
![屏幕截图(41)](https://user-images.githubusercontent.com/131774725/235619315-e80b4732-8599-4146-a0d5-5ba232ad0e89.png)

**运行环境 (请完善以下信息):**
 - 系统：Linux centOS6
 - Python环境版本:python3.9
 - 运行方式: 源代码运行
 - 代码版本:

**其他内容**
我看过openssl中支持的加密套件是包含了超星网站的加密套件的

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
