### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by Jeremy-cell** [Samueli924/chaoxing#245]
**形容Bug的信息**

**Screenshots**
![image](https://github.com/Samueli924/chaoxing/assets/56188037/ebc06fb4-6a79-44b0-9759-87fcfc9b0a85)

**运行环境 (请完善以下信息):**
 - 系统：Windows10
 - Python环Windows境版本:python 3.12
 - 运行方式: 源代码运行
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
