### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by xANoyU** [Samueli924/chaoxing#25]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
foreWork.py:142 foreWork.py:141
**Screenshots**
插入程序出现BUG的截图

![image](https://user-images.githubusercontent.com/62326160/138213797-7dcdd5fd-96f9-437d-9f70-42a907e81cfd.png)

![image](https://user-images.githubusercontent.com/62326160/138214502-beb5fe08-355d-42d5-aef7-e93189412574.png)

课程后边的视频没有刷
**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Windows
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 3.9.7
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - py main.py
 - 代码版本:[比如0.5.0,1.0.0]
 - 直接download zip的

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by xz454867105** [comment]
因为我最初写这个的时候我的课程里只有mp4、ppt、pdf格式的任务点，我也只能爬取到这三类的数据，这个代码可以完成所有的mp4、ppt和pdf任务，针对大多数的课程完成度已经可以有70-80%。
详情可以看这个[issue](https://github.com/xz454867105/chaoxing/issues/17)

**Comment by xz454867105** [comment]
可能视频格式不是mp4？

**Comment by xz454867105** [comment]
如果有能力可以试试顺着代码抓取输出一遍返回值，看看为什么返回的内容不是json
