### ISSUE TITLE
[BUG反馈] 很抱歉，您没有权 限访问这个页面！code=6 

### ISSUE THREAD

**Issue by Last-ID** [Samueli924/chaoxing#251]
**形容Bug的信息**
读取完标签信息后报错退出
**Screenshots**
![image](https://github.com/Samueli924/chaoxing/assets/44721512/bbd2c736-bbdf-4884-85be-9028c1112649)

**运行环境 (请完善以下信息):**
 - 系统：Windows, 和CentOS均有这个问题
 - Python环境版本:Python3.8
 - 运行方式: **源代码运行**与**可执行文件exe运行**
 - 代码版本:最新Release

**其他内容**
可能是学习通反爬机制导致的

**Comment by Mishaoc** [comment]
同问

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
