### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by HNUrookie1** [Samueli924/chaoxing#256]
**形容Bug的信息**
195行错误
**Screenshots**
![image](https://github.com/Samueli924/chaoxing/assets/102892887/657673c4-89f7-40f1-a77e-42a3399895b3)

**运行环境 
 - 系统：
![image](https://github.com/Samueli924/chaoxing/assets/102892887/42c2d345-4cd2-4549-b7cc-7b1828f1ba82)

 - Python环境版本:Python3.10
 - 运行方式: 源代码运行
 - 代码版本:最新版的  截止2023-06-27

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
