### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Hentai02** [Samueli924/chaoxing#260]
**形容Bug的信息**
刚开始还能登录获取课程，但是无法刷课提示章节错误，重新登陆之后一直提示
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：C:\Users\Hentai\AppData\Local\Temp\_MEI131322\main.py
错误行数：158
错误原因:Expecting value: line 1 column 1 (char 0)
删了还是会提示这个错误

**Screenshots**
![image](https://github.com/Samueli924/chaoxing/assets/54672936/e0df045f-d14c-49c6-bc07-6941ace5c0ab)

**运行环境 (请完善以下信息):**
 - 系统：Windows 10 22H2 19045.3324
 - 运行方式: 可执行文件exe运行
 - 代码版本:2.4.4

**其他内容**
不想看那些没啥用的课

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
