### ISSUE TITLE
ubuntu20.04 安装Python3.9以上以及项目搭建过程问题

### ISSUE THREAD

**Issue by StayOne1** [Samueli924/chaoxing#262]
pip install -r requirements.txt 时出现报错，无法安装maskpass，单独pip install maskpass发现错误原因：Python11 No module named '_ctypes'。 
解决：
1 . sudo apt-get install libffi-dev
2. 重新构建Python ： 切换到Python安装目录 后： sudo make install
3. 切换到项目路径后： pip install -r requirements.txt

如有其他报错： 检查Python版本与Pip版本（是否对应）pip --version、使用国内Pip源

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
