### ISSUE TITLE
这个问题怎么办[Question]

### ISSUE THREAD

**Issue by dxmkdw** [Samueli924/chaoxing#266]
(venv) PS D:\浏览器下载\chaoxing-main> python main.py
Traceback (most recent call last):
  File "D:\浏览器下载\chaoxing-main\main.py", line 6, in <module>
    from api.chaoxing import Chaoxing
  File "D:\浏览器下载\chaoxing-main\api\chaoxing.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
用pip install Crypto 后还会出现
(venv) PS D:\浏览器下载\chaoxing-main> pip install Crypto
Requirement already satisfied: Crypto in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (1.4.1)
Requirement already satisfied: Naked in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from Crypto) (0.1.32)
Requirement already satisfied: shellescape in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from Crypto) (3.8.1)
Requirement already satisfied: requests in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from Naked->Crypto) (2.31.0)
Requirement already satisfied: pyyaml in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from Naked->Crypto) (6.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from requests->Naked->Crypto) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from requests->Naked->Crypto) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from requests->Naked->Crypto) (1.25.11)    
Requirement already satisfied: certifi>=2017.4.17 in d:\浏览器下载\chaoxing-main\venv\lib\site-packages (from requests->Naked->Crypto) (2023.7.22)  
(venv) PS D:\浏览器下载\chaoxing-main> python main.py
Traceback (most recent call last):
  File "D:\浏览器下载\chaoxing-main\main.py", line 6, in <module>
    from api.chaoxing import Chaoxing
  File "D:\浏览器下载\chaoxing-main\api\chaoxing.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
