### ISSUE TITLE
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！

### ISSUE THREAD

**Issue by BJ-MQC** [Samueli924/chaoxing#269]
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！
超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！

**Comment by WFCrush** [comment]
代

**Comment by WFCrush** [comment]
私聊q2496738519




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samuel ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Samueli924/chaoxing] 超星新增了人脸识别，请求大佬增加人脸识别功能！！！！！！！ (Issue #269)





 
Closed #269 as completed.
