### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Berger10086** [Samueli924/chaoxing#271]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![image](https://github.com/Samueli924/chaoxing/assets/78753488/b73310aa-357d-43e7-85ad-034493d1750b)
一直处于获取标签状态

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by qwe8511066** [comment]
+1

**Comment by Zxz8964** [comment]
源代码运行不会出现这种状况，可以试着在win10下用pyinstaller打包再跑
![图片](https://github.com/Samueli924/chaoxing/assets/104437672/171c477f-6974-477d-b275-189a543b8dbb)

**Comment by Zxz8964** [comment]
我这里有打包好的文件，不放心的话可以按教程里的步骤自己打包
[pyinstaller打包.zip](https://github.com/Samueli924/chaoxing/files/12916334/pyinstaller.zip)
