### ISSUE TITLE
[Advice]mac运行报错

### ISSUE THREAD

**Issue by VBME** [Samueli924/chaoxing#272]
**清晰有逻辑的提出问题**
详细内容
<img width="570" alt="image" src="https://github.com/Samueli924/chaoxing/assets/29477082/e009a77d-234e-4579-a326-b26a4879d9c8">

**Comment by VBME** [comment]
救我

**Comment by SpiralTower** [comment]
编辑main.py文件，前头加  # coding=utf-8 试试

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
