### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by zearo-github** [Samueli924/chaoxing#282]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
![image](https://github.com/Samueli924/chaoxing/assets/90169120/6aed3827-9c44-402a-b548-797615dadd10)

**运行环境 (请完善以下信息):**
 - 系统：Windows
 - Python环境版本:[比如:Python2,Python3.6,Python3.8]
 - 运行方式:可执行文件exe运行

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
