### ISSUE TITLE
[Feature Request]大家如果遇到403的话可以试下这样做

### ISSUE THREAD

**Issue by DavidMastrenet** [Samueli924/chaoxing#283]
**这个功能建议是否与使用过程中出现的BUG有关**
我在刷心理课的时候使用代码出现403报错，经过研究发现脚本中的rt是0.9，自己抓（浏览器）包发现心理课的rt是1，脚本api/chaoxing.py里面rt改成1就可以刷了

**描述你想添加的功能**
目前还没发现这个rt是从哪里下传的，等我有空研究下，大家如果有发现的话也可以pr捏。

**补充内容**
<img width="741" alt="image" src="https://github.com/Samueli924/chaoxing/assets/47383241/621348db-465b-46c6-ac4c-30d656f2f845">

**Comment by FeletexGee** [comment]
兄啊，今天也遇到了（悲）

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
