### ISSUE TITLE
[Feature Request] 多课程&全部课程-功能改进请求

### ISSUE THREAD

**Issue by Cherish1993** [Samueli924/chaoxing#284]
- 本人入职培训涉及40多个课程，涉及的视频超级多，每次选择起来非常痛苦~
- 希望各位项目组的大佬能够帮忙改进一下，以新增如下功能：
         ① 同时选择多个课程序号；② 一键进行全部课程学习。
- 我自己尝试进行修改，但是只能够实现简单的循环，并未能解决需求，特此求助。

**Comment by DavidMastrenet** [comment]
主函数循环，index递增就可以了

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
