### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by wander303** [Samueli924/chaoxing#286]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
无法登录

**Screenshots**
![截图](https://github.com/Samueli924/chaoxing/assets/108849052/f84d72ac-80ec-46d2-8702-b5331b4f94b0)
**运行环境 (请完善以下信息):**
 - 系统：ubuntu 20.04
 - Python环境版本:python 3.8
 - 运行方式:源代码运行
 - 代码版本:2.4.5

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
已更新最新版本，如仍有问题请重开Issue，谢谢
