### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Cm1316** [Samueli924/chaoxing#295]
获取课程为0![image](https://github.com/Samueli924/chaoxing/assets/114371246/030522d3-8cdd-41ea-9459-ce8662ffa6cf)

**Comment by Cm1316** [comment]
试了几个账号都是这种情况

**Comment by Cm1316** [comment]
等我回去把日志发给你一下，不清楚为什么账号情况可以获取，课程无法获取

**Comment by Cm1316** [comment]
运行系统：MacOs
运行版本：3.10
出现问题：课程获取始终为零
mian.py执行文件报错

**Comment by Samueli924** [comment]
麻烦把config文件的course_list项截图看一下

**Comment by Samueli924** [comment]
最新版本应该是修复了这个问题 你可以拉取最新版本试试

**Comment by Cm1316** [comment]
上传了4张图片两张是输入id和留空出现的运行结果!![image](https://github.com/Samueli924/chaoxing/assets/114371246/629da77b-3834-406f-b4f9-a383dfddb789)![image](https://github.com/Samueli924/chaoxing/assets/114371246/87628f76-6541-4d50-80d7-06ef028f37e8)


还有一张是运行第5命令代码报错
![image](https://github.com/Samueli924/chaoxing/assets/114371246/815b56ac-4b46-47f8-aedf-43551352789e)/Users/chengmu/PycharmProjects/chaoxing/venv/bin/python main.py -u 手机号 -p 密码 -l 课程ID1,课程ID2,课程ID3...(可选) 
2023-11-15 12:31:45.327 | ERROR    | api.exceptions:__init__:6 - 用户名或密码错误
Traceback (most recent call last):
  File "/Users/chengmu/PycharmProjects/chaoxing/main.py", line 40, in <module>
    raise LoginError(_login_state["msg"])
api.exceptions.LoginError: 用户名或密码错误

进程已结束，退出代码为 1
以及第40行代码![image](https://github.com/Samueli924/chaoxing/assets/114371246/b3359ba5-8f60-45bb-84b5-6f3d871b6669)

**Comment by Cm1316** [comment]
> 最新版本应该是修复了这个问题 你可以拉取最新版本试试

呜呜，还是不行😭

**Comment by Samueli924** [comment]
course_list这一栏要么是留空
course_list: 

要么是填入ID:
course_list: 125125141,12452151,51243124

你再试试

**Comment by Cm1316** [comment]
感谢，完美解决了🥹🥹🥹，我基础不好，忘了是这样留空的

**Comment by Cm1316** [comment]
作者可以直接把源码=改为：，：（课程代码），可以替代=（课程代码），以防后面有人像我一样傻😂🤣
