### ISSUE TITLE
[BUG反馈]遇到无法播放的视频 会中断程序

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing#298]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
遇到无法播放的视频会中断程序 但后面的视频能够正常播放
```
Traceback (most recent call last):
  File "D:\code\chaoxing\main.py", line 67, in <module>
    jobs, job_info = chaoxing.get_job_list(course["clazzId"], course["courseId"], course["cpi"], point["id"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\chaoxing\api\base.py", line 111, in get_job_list
    _job_list, _job_info = decode_course_card(_resp.text)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\chaoxing\api\decode.py", line 84, in decode_course_card
    _job["mid"] = _card["mid"]
                  ~~~~~^^^^^^^
KeyError: 'mid'
```
**Screenshots**
插入程序出现BUG的截图
![image](https://github.com/Samueli924/chaoxing/assets/64531014/1a3511a7-4bf5-4096-8cc7-9636eabef493)

**运行环境 (请完善以下信息):**
 - 系统：[比如:Windows,macOS,Linux(精确到发行版本名)] window10
 - Python环境版本:[比如:Python2,Python3.6,Python3.8] python3.10
 - 运行方式: [比如:源代码运行,可执行文件exe运行,打包bat文件运行] 源码
 - 代码版本:[比如0.5.0,1.0.0] commit 6c7cd9ac02897727188b5448c5254e6c4893243f

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
感谢反馈 已在最新版本修复
