### ISSUE TITLE
[Feature Request] 使用noneprompt优化用户体验

### ISSUE THREAD

**Issue by H2Sxxa** [Samueli924/chaoxing#303]
感觉有优化空间，但会增加应用体积，不知道您会不会介意，需要帮助的话我可以提供Pull Request（

https://github.com/nonebot/noneprompt

## InputPrompt

```python
from noneprompt import InputPrompt
from noneprompt import ListPrompt

phone = InputPrompt("输入手机号").prompt()
pwd = InputPrompt("输入密码", is_password=True).prompt()
print(phone, pwd)
```

![动画](https://github.com/Samueli924/chaoxing/assets/88923783/a7aca545-fa92-4ecd-85a7-707acc40ef0c)

## ListPrompt

```python
from noneprompt import ListPrompt, Choice

lp = ListPrompt(
    question="选择课程", choices=[Choice("课程1", 1), Choice("课程2", 2), Choice("课程3", 3)]
).prompt()

print(lp.data)
```
![动画](https://github.com/Samueli924/chaoxing/assets/88923783/dcb3fbef-37fd-4f38-8dc0-6f56f7ca278f)

**Comment by WuhuVoV** [comment]
噶

**Comment by WuhuVoV** [comment]
求
