### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by djzhhil** [Samueli924/chaoxing#305]
![微信图片_20231130001700](https://github.com/Samueli924/chaoxing/assets/80150227/9cffc6ae-35f3-4320-94f6-257d60d61fd2)

**Comment by syjjx** [comment]
api/decode.py文件中的55行 修改为 return None,None即可
顺便说下，当前版本下 speed参数只是在显示上有效，实际效果不佳
get_job_list()方法内请求的url，其实num参数固定为0，会导致只能学习第一P的，实际课程中有多P的就没法处理，将其修改为0-4的遍历即可

**Comment by syjjx** [comment]
_isPassed = self.video_progress_log(_session, _course, _job, _job_info, _dtoken, _duration, 0)
最后一个参数建议传入实际的_playingTime
show_progress()方法中，修改为current = start + int(time.time() - start_time)*_speed
这样每个课程的学习时间基本可以固定在原本的1/2

**Comment by Samueli924** [comment]
已修复
