### ISSUE TITLE
[BUG反馈] 非预期的JSON格式

### ISSUE THREAD

**Issue by DmTomHL** [Samueli924/chaoxing#306]
**代码报错截图**
![反馈](https://github.com/Samueli924/chaoxing/assets/119683924/d0bbd133-a66e-4915-99f7-bc6e6bff31d6)
如图
我使用vps来运行脚本来确定不是我的网络问题，请问该如何修复呢
百忙之中给您添麻烦了，抱歉

**Comment by wkz2003** [comment]
同样的错误，解决了吗兄弟

**Comment by Samueli924** [comment]
已修复
