### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by FONG4514** [Samueli924/chaoxing#308]
**网页端课程报错任务点截图**
[
![0M2D68NPYYY381}BC2`RJ`1](https://github.com/Samueli924/chaoxing/assets/126694385/edee6556-185d-4d1e-a012-def3c1c1f452)
](url)
无法获取课程列表
使用腾讯云的服务器，系统是centos7.6，python版本是3.7.6，pip版本是23.3.1，代码版本3.0.3，使用python main.py启动

**Comment by Samueli924** [comment]
已由(Lei Ye)[https://github.com/41369ly]于[PR #309](https://github.com/Samueli924/chaoxing/pull/309)中修复

**Comment by Samueli924** [comment]
已由[Lei Ye](https://github.com/41369ly)于[PR #309](https://github.com/Samueli924/chaoxing/pull/309)中修复
