### ISSUE TITLE
[BUG反馈]运行main.py出错

### ISSUE THREAD

**Issue by yehuzhucha** [Samueli924/chaoxing#312]
[如图](https://s11.ax1x.com/2023/12/17/pi50yx1.jpg)
不管用哪一种方式运行，都提示这个

**Comment by yehuzhucha** [comment]
[图](https://s11.ax1x.com/2023/12/17/pi50yx1.jpg)

**Comment by 41369ly** [comment]
不应该啊，这提示语法错误 你用的什么python版本

**Comment by WuhuVoV** [comment]
缺少模块

**Comment by Samueli924** [comment]
得使用Python3运行哈，你这个是Python2
