### ISSUE TITLE
[BUG反馈]二级目录课程不显示

### ISSUE THREAD

**Issue by FeletexGee** [Samueli924/chaoxing#313]
**Issue**
如果在课程列表中设置了任何二级目录（如图）：
![image](https://github.com/Samueli924/chaoxing/assets/69303837/1dbac606-acd4-4a1e-bc3b-a9d77326cd25)

则会无法读取到二级目录中的课程：
![image](https://github.com/Samueli924/chaoxing/assets/69303837/549ad490-9780-4ba3-bfb2-a0d9e2272625)

**Solution**
去做了code review，又调用了一下API，课程遍历方式应该是没有问题的……好奇怪

**Comment by WuhuVoV** [comment]
bs4解析网页时报错：bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

原因：不可以使用 BeautifulSoup(html,'html_parser')

解决办法：

1.安装 pip install lxml

2.将BeautifulSoup(html,'html_parser') 改为BeautifulSoup(html,'lxml')
