### ISSUE TITLE
[BUG反馈]requests

### ISSUE THREAD

**Issue by WuhuVoV** [Samueli924/chaoxing#316]
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 41369ly** [comment]
issues能不能提得规范一点，这点信息谁能找到问题啊，连代码行数都没有

**Comment by Samueli924** [comment]
已修复
