### ISSUE TITLE
[BUG反馈]出现无权访问错误

### ISSUE THREAD

**Issue by dong-dong6** [Samueli924/chaoxing#318]
**代码报错截图**
此处上传代码报错处截图
![image](https://github.com/Samueli924/chaoxing/assets/73739354/2e789033-e76d-41a1-aeef-d02e9f9a5fc7)

**网页端课程报错任务点截图**
此处上传出现报错的任务点的网页端截图
![image](https://github.com/Samueli924/chaoxing/assets/73739354/cee234fc-0c17-454c-824f-57c3546a2417)

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
你这个版本是很早很早以前的，要拉取最新版本的代码
