### ISSUE TITLE
[BUG反馈]出现异常章节，代码不可刷，网页端可看

### ISSUE THREAD

**Issue by dong-dong6** [Samueli924/chaoxing#319]
**代码报错截图**
此处上传代码报错处截图
![image](https://github.com/Samueli924/chaoxing/assets/73739354/e2bf247b-7d00-4e65-99d5-bbc9a00b973a)

**网页端课程报错任务点截图**
此处上传出现报错的任务点的网页端截图
![image](https://github.com/Samueli924/chaoxing/assets/73739354/ed3a97c5-ae88-47db-b76d-e471798d16f1)

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
能不能帮忙截一下网页的抓包
打开F12-网络
然后开始播放视频
找到multimedia/log这一个
然后把请求链接和请求头给截个图
谢谢

**Comment by dong-dong6** [comment]
![image](https://github.com/Samueli924/chaoxing/assets/73739354/3062105f-6313-471f-a9ca-f5e5fdc81465)
是这个吗？

**Comment by Samueli924** [comment]
对的 你把base.py第157行的rt=0.9&改成rt=1&试试
![image](https://github.com/Samueli924/chaoxing/assets/65054820/4ea22352-7be2-443c-92ca-e66b96dabdc0)

**Comment by dong-dong6** [comment]
ok，开始正常播放了

**Comment by dong-dong6** [comment]
这样的话，正常为0.9的课程又刷不起来了，怎么写个判断吗？

**Comment by tuyouyu** [comment]
这个参数是啥意思，除了0.9、1 还有其它类型吗？如果不多，只能写个判断，循环尝试了。或者手动传参
