### ISSUE TITLE
[BUG反馈]章节任务点读取成功后程序直接退出

### ISSUE THREAD

**Issue by HexStan** [Samueli924/chaoxing#320]
**代码报错截图**
代码无报错，log无记录，直接退出
![image](https://github.com/Samueli924/chaoxing/assets/34975883/ea421be4-bbd1-4e3b-a67d-2b59ff28663d)

**网页端课程报错任务点截图**
![image](https://github.com/Samueli924/chaoxing/assets/34975883/0d2dfd5d-dd7c-48d6-83d3-b2f89e07486f)

**其他内容**
终端运行记录：
![image](https://github.com/Samueli924/chaoxing/assets/34975883/22bf7132-b5d8-4205-80b9-159cee936529)

**Comment by INKCR0W** [comment]
我也出现了相同的问题，并且这个问题只出现在了一个课程上，这个课程是一个courseid有两个班级，如图
![6e2e70a8bf9076a1f3c986a8b203ae7e](https://github.com/Samueli924/chaoxing/assets/119268906/bc1789ba-08bd-4011-bf3f-bb000acfbc12)

在读取课程列表时就有两个相同的结果，当输入课程ID后，正常读取任务点，读取结束后会直接退出

**Comment by INKCR0W** [comment]
定位到了问题，在[这里](https://github.com/Samueli924/chaoxing/blob/main/api/base.py#L128)
把链接中的num参数修改为1，就可以正常获取任务节点了
为0时会一直得到第一个节点，导致只能完成每节课的第一个任务点
只在我自己的一个课程上做过测试，不知这个参数的含义，也没有测试过通用性
希望能帮助解决问题

**Comment by INKCR0W** [comment]
P.S.
不确定是否只出现在有多个clazzid的情况，没有做过测试
