### ISSUE TITLE
[BUG反馈]无法获取课程列表

### ISSUE THREAD

**Issue by dong-dong6** [Samueli924/chaoxing#323]
**代码报错截图**
此处上传代码报错处截图
![image](https://github.com/Samueli924/chaoxing/assets/73739354/b3dfcd97-105a-4c34-9712-137dd32ea465)
![image](https://github.com/Samueli924/chaoxing/assets/73739354/76536755-0b4b-4b31-ad9d-28658028ca4a)

**Comment by Samueli924** [comment]
这个不是任务点，只有标注了任务点的课程内容才会完成的。
