### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by cqep** [Samueli924/chaoxing#328]
**代码报错截图**
无

**网页端课程报错任务点截图**
无

**其他内容**
希望大佬可以加入账号密码记忆的功能 这样不用每一次都输入账号密码了

**Comment by 41369ly** [comment]
<img width="917" alt="image" src="https://github.com/Samueli924/chaoxing/assets/51309038/391dccfe-ddd2-45cb-ad8d-4b3cdf15c7d0">
本来就可以使用配置文件读取用户名密码，请看readme
