### ISSUE TITLE
[BUG反馈]直播课没法刷

### ISSUE THREAD

**Issue by w1cherr** [Samueli924/chaoxing#332]
**代码报错截图**

**网页端课程报错任务点截图**
此处上传出现报错的任务点的网页端截图

**其他内容**
直播类型的课全都没法刷，大佬能不能考虑下支持刷直播课

**Comment by Samueli924** [comment]
我现在已经没有啥空余时间给这个库添加新功能了，可以等看有没有其他开发者可以为这个库提交PR更新功能。
