### ISSUE TITLE
你好，想问一下，后期可以增加一个题库，刷课堂作业嘛？

### ISSUE THREAD

**Issue by ice789ice** [Samueli924/chaoxing#337]
**代码报错截图**
此处上传代码报错处截图

**网页端课程报错任务点截图**
此处上传出现报错的任务点的网页端截图

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
这个需要更新频率有些高，我现在已经没有啥空余时间给这个库添加新功能了，可以等看有没有其他开发者可以为这个库提交PR更新功能。
