### ISSUE TITLE
[BUG反馈]releases文件需要更新

### ISSUE THREAD

**Issue by wy3057** [Samueli924/chaoxing#339]
**代码报错截图**
此处上传代码报错处截图

**网页端课程报错任务点截图**
此处上传出现报错的任务点的网页端截图

**其他内容**
您觉得对问题反馈有帮助的内容
releases 的exe文件有问题
目前需要从源码文件运行
希望可以更新一下releases的exe文件，重新打包一下
感谢

**Comment by Samueli924** [comment]
已更新。
