### ISSUE TITLE
[BUG反馈]出现异常任务 

### ISSUE THREAD

**Issue by LSeaPDynasty** [Samueli924/chaoxing#341]
![3eec132aea3616211cb1969750c29d83](https://github.com/Samueli924/chaoxing/assets/147352882/53b0b02e-23b2-4d3e-8d59-ceae5e2fb926)
![3eec132aea3616211cb1969750c29d83](https://github.com/Samueli924/chaoxing/assets/147352882/53b0b02e-23b2-4d3e-8d59-ceae5e2fb926)
![3eec132aea3616211cb1969750c29d83](https://github.com/Samueli924/chaoxing/assets/147352882/53b0b02e-23b2-4d3e-8d59-ceae5e2fb926)
视频解析错误

![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()

**Comment by LSeaPDynasty** [comment]
额，图片提交的有点问题，见谅

**Comment by LSeaPDynasty** [comment]
![Uploading 46f4af230aad6ff3d2c4883a5c6e6b26.png…]()

**Comment by Samueli924** [comment]
已修复BUG
