### ISSUE TITLE
增加自动答题功能的讨论

### ISSUE THREAD

**Issue by EnderTheCoder** [Samueli924/chaoxing#345]
希望能够增加自动答题功能，但是不清楚学习通的题库API如何获取，请问作者是否有这方面的思路？如果能解决题库问题我可以交个PR来支持这个功能。

**Comment by JokerJostar** [comment]
用第三方题库的api，参考这个repo[https://github.com/SocialSisterYi/CxKitty](url)

**Comment by Samueli924** [comment]
已添加第三方题库接口
