### ISSUE TITLE
任务点怎么过

### ISSUE THREAD

**Issue by tonylxt** [Samueli924/chaoxing#348]
首先感谢作者Samueli924。我在用这个工具时，出现两个问题：第一、每个培训视频只学习到99%或者98%的进度，手动进页面，原来是视频的任务点没有过，目前我是手动过的；第二、如果任务点没过，下次重新进入学习时，会从头学，而不是接着上次的进度学。

**Comment by tonylxt** [comment]
知道问题出在哪里了，自己修改了一处代码，问题解决了

**Comment by eunrui** [comment]
可以提个pr吗

**Comment by tonylxt** [comment]
当然可以，我经过测试，发现问题好像是出在 base.py 中的 def study_video 里。注意这几句：
if _playingTime + _wait_time >= int(_duration):
                    _wait_time = int(_duration) - _playingTime
                    _isFinished = True
它会让视频播放还没有结果时，提前让 _isFinished 为真，这是问题的关键。
如果我说的不对，见谅
最后，感谢你们为大家提供这个程序。
