### ISSUE TITLE
[BUG反馈] 章节测验任务点无法完成

### ISSUE THREAD

**Issue by MerukYang** [Samueli924/chaoxing#352]
**代码报错截图**
此处上传代码报错处截图

**网页端课程报错任务点截图**
![1232434](https://github.com/user-attachments/assets/2476a327-0d77-4a14-8625-ec7b6c40141f)
![无标题4547567657](https://github.com/user-attachments/assets/fa8d8790-69f9-41b5-8dde-9251c49acd96)

**其他内容**
章节测验任务点无法完成（见上截图）。我从零开始使用本项目提供的应用程序进行刷课，在已完成第一章第一节及第二节的学习后（即目前正在第三节的刷课），查看进度后，发现任务点仍有剩余。经浏览，系章节测验任务未完成。
应用程序未报错。

btw，请密切关注 #348 的内容及相关PR。

**Comment by Samueli924** [comment]
目前程序是不支持章节测验任务的，所有的章节测验任务都会默认被跳过
