### ISSUE TITLE
视频任务建议

### ISSUE THREAD

**Issue by cuo-ren** [Samueli924/chaoxing#356]
在网页端可以通过global speed实现视频16倍速学习，不知道这个项目能否实现

**Comment by Samueli924** [comment]
实际操作上是可以实现的，但是我们为了防止超星的心跳检测发现正在使用脚本，限制了最大速度为2倍，如果想要使用大于2倍速，可以在ini配置文件中设置speed倍速，然后修改`main.py`文件的第57行`speed = min(2.0, max(1.0, speed))`为`speed = 你想要的倍速`
