### ISSUE TITLE
[BUG反馈] 无法读取课程列表

### ISSUE THREAD

**Issue by Ljh000000** [Samueli924/chaoxing#362]
2024-10-19 00:53:09.133 | INFO     | api.base:login:72 - 登录成功...
2024-10-19 00:53:09.368 | INFO     | api.base:get_course_list:97 - 课程列表读取完毕...
**********课程列表**********
****************************
请输入想要学习的课程列表,以逗号分隔,例: 2151141,189191,198198

**Comment by sz134055** [comment]
接口好像抽风了，如果你用的是源码而不是打包的，修改api/base.py下，在101行左右的代码：
```python
_resp = _session.post(_url, data=_data)
```
改成
```python
        _headers = {
            "Host": "mooc2-ans.chaoxing.com",
            "sec-ch-ua-platform": "\"Windows\"",
            "X-Requested-With": "XMLHttpRequest",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
            "Accept": "text/html, */*; q=0.01",
            "sec-ch-ua": "\"Microsoft Edge\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"",
            "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
            "sec-ch-ua-mobile": "?0",
            "Origin": "https://mooc2-ans.chaoxing.com",
            "Sec-Fetch-Site": "same-origin",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Dest": "empty",
            "Referer": "https://mooc2-ans.chaoxing.com/mooc2-ans/visit/interaction?moocDomain=https://mooc1-1.chaoxing.com/mooc-ans",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,ja;q=0.5"
        }
        _resp = _session.post(_url,headers=_headers,data=_data)
```
注意缩进

**Comment by AfishInLake** [comment]
_url = "https://mooc2-ans.chaoxing.com/mooc2-ans/visit/courselistdata"
这个接口需要添加下面的headers才能正常访问，否则就是403
COURSELIST_HEADERS = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
        "Origin": "https://mooc2-ans.chaoxing.com",
        "Referer": "https://mooc2-ans.chaoxing.com/mooc2-ans/visit/interaction?moocDomain=https://mooc1-1.chaoxing.com/mooc-ans",
        "X-Requested-With": "XMLHttpRequest"
    }
