### ISSUE TITLE
[数组越界]

### ISSUE THREAD

**Issue by abyss-stars** [Samueli924/chaoxing#374]
**代码报错截图**

<img width="854" alt="1730428850136" src="https://github.com/user-attachments/assets/39d4600d-50a3-47bd-a0c8-6424d1c860f8">

**其他内容**
9.1前配置题库后回答问题正常
之后报错为数组越界

**Comment by Samueli924** [comment]
@sz134055

**Comment by sz134055** [comment]
感觉是多选题答案没切割好的问题，你从我仓库拉一下我修改后的dev分支代码试试看还有没有问题，有问题我再看看：
```bash
git clone -b dev https://github.com/sz134055/chaoxing.git
```

**Comment by abyss-stars** [comment]
<img width="859" alt="1730561196243" src="https://github.com/user-attachments/assets/b7f56566-0305-4188-927d-95f4b1f73ab8">
可以了，十分感谢
