### ISSUE TITLE
win版没办法调速率了吗 希望可以在软件内随时调速率

### ISSUE THREAD

**Issue by YANGNIGHT** [Samueli924/chaoxing#41]
**这个功能建议是否与使用过程中出现的BUG有关**
详细的描述

**描述你想添加的功能**
详细的描述

**补充内容**
可以上传截图或文字表达补充建议

**Comment by Samueli924** [comment]
win版可以在启动前统一调速率
你可以把库目录下的config.ini内容下载到exe文件目录里，修改好config.ini内容(里面可以设置倍速)
再用命令行执行chaoxing_2.0.5.exe -c

**Comment by Samueli924** [comment]
软件内随时调速率的功能我可以在之后添加可视化UI界面，用多线程重新改一遍。但是近期因为比较忙，可能得到明年初才有时间加入这些功能。

**Comment by YANGNIGHT** [comment]
> 软件内随时调速率的功能我可以在之后添加可视化UI界面，用多线程重新改一遍。但是近期因为比较忙，可能得到明年初才有时间加入这些功能。

哦哦 好的 我以为更新后就不能用配置文件启动了 还有刚刚用python运行时报错 [Errno 13] Permission denied: 'saves/17707429519/219121216'
是记录的这个文件夹出错了吗  还有像这样没有显示有几个任务的好像会说无法识别任务类型 只能自己再手动刷
![图片](https://user-images.githubusercontent.com/79457406/143439934-6fd44c87-8168-485e-bfbd-932a385b6a4b.png)
另外我的课都在你这里完成的 感谢啦

**Comment by Samueli924** [comment]
这个Permission denied的报错一般是路径错误之类的问题，但是看你这个'saves/17707429519/219121216'路径是没有问题的。如果你能把你报错后saves目录底下的两层都截个图我排个错就非常感谢了！

根据你的这个截图看到这个任务好像是没有计入任务点的，也就是说这个课程的完成度和这几个小节是没有关系的。然后我用的接口是获取课程中计入任务点的任务，所以像这样的小节在代码里是直接被忽略了。

不用谢，这个项目本来的目的就是帮助大家免去一些浪费时间的没有意义的课程任务！

**Comment by YANGNIGHT** [comment]
我也不知道是不是我所用的平台问题  但之前都是能用的 刚刚突然用不了了 然后在saves/17707429519/219121216目录下找不到这个219121216
![1](https://user-images.githubusercontent.com/79457406/143443387-6a4fe9d0-5179-4ae9-b779-faffdfcc8738.jpg)
![2](https://user-images.githubusercontent.com/79457406/143443402-89344d02-fc10-4df0-863f-7dab1b84771a.jpg)

**Comment by Samueli924** [comment]
报错日志看起来是在初始化课程文件夹的时候新建文件夹失败，报错码是说没有创建文件夹的权限。
我不确定为什么会出现。
    之前都是能用的 刚刚突然用不了
但是可以确定问题在于用户文件夹，也就是17707429519这个文件夹的读写权限有问题，你可以尝试用管理员把这个文件夹的权限改成0777或0775试试
-------
不想折腾的话，最简易的方法还是直接删除saves文件夹，然后重新运行

**Comment by YANGNIGHT** [comment]
我重新看了下 如果本地没有这堂课的记录 就能继续开始任务 但如果已经开始了这个课程 然后退出想继续刷这个课程的话就会报错 win端运行python没有问题 所以可能是手机的限制吧  麻烦你了
