### ISSUE TITLE
[BUG反馈]获取课程报错

### ISSUE THREAD

**Issue by Montaro2017** [Samueli924/chaoxing#44]
**形容Bug的信息**
运行代码，输入账号密码之后获取课程报错

**Screenshots**
![err](https://user-images.githubusercontent.com/35142778/144793029-5f423900-2be8-4392-b8a0-b88887e35641.png)

**运行环境 (请完善以下信息):**
 - 系统：CentOS Linux release 7.9.2009 (Core)
 - Python环境版本:Python3
 - 运行方式: 源代码运行
 - 代码版本:2.0.5

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
你好，我更新了最新的代码。在出现报错时会把相关的日志输出出来。如果可以，麻烦你拉取最新代码，然后重新运行，将报错的日志再截图上传，谢谢

**Comment by Montaro2017** [comment]
> 你好，我更新了最新的代码。在出现报错时会把相关的日志输出出来。如果可以，麻烦你拉取最新代码，然后重新运行，将报错的日志再截图上传，谢谢

![image](https://user-images.githubusercontent.com/35142778/144795484-1e1b8f04-9a7f-44c4-83f4-096e6a6622a5.png)

我看readme里不能使用阿里云的服务器，于是我想试试腾讯云的服务区，似乎腾讯云的也不可以了

**Comment by Samueli924** [comment]
![Snipaste_2021-12-06_14-08-59](https://user-images.githubusercontent.com/65054820/144796156-8c58c75e-f6c2-4ff3-81c1-1453fd342124.png)

----

我测试了一下我自己的腾讯云，运行是正常的，超星获取所有课程的API接口是[https://mooc1-api.chaoxing.com/mycourse](https://mooc1-api.chaoxing.com/mycourse)你可以尝试在本地浏览器登录后打开，假如返回的数据正常，就有可能是IP段被屏蔽的问题。

----

如果不嫌麻烦，可以挂代理。但我还是不建议在服务器运行

**Comment by Montaro2017** [comment]
> ![Snipaste_2021-12-06_14-08-59](https://user-images.githubusercontent.com/65054820/144796156-8c58c75e-f6c2-4ff3-81c1-1453fd342124.png)
> 
> 我测试了一下我自己的腾讯云，运行是正常的，超星获取所有课程的API接口是https://mooc1-api.chaoxing.com/mycourse你可以尝试在本地浏览器登录后打开，假如返回的数据正常，就有可能是IP段被屏蔽的问题。
> 
> 如果不嫌麻烦，可以挂代理。但我还是不建议在服务器运行

本地试过了，是正常的，看来是IP段被屏蔽了
