### ISSUE TITLE
[BUG反馈]exe运行出现错误

### ISSUE THREAD

**Issue by 1578339936** [Samueli924/chaoxing#55]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
当前视频:<font color=Red>xx</font><font color=Red>xx</font>，xxxx——<font color=Red>xx</font>xxxxxxxxx
当前任务： <font color=Red>xx</font><font color=Red>xx</font>，xxxx——<font color=Red>xx</font>xxxxxxxxx 已完成

当前视频:<font color=Red>xx</font><font color=Red>xx</font>，xxxx——<font color=Red>xx</font>xxxxxxxxx
当前任务： <font color=Red>xx</font><font color=Red>xx</font>，xxxx——<font color=Red>xx</font>xxxxxxxxxx 已完成
Traceback (most recent call last):
  File "main.py", line 106, in <module>
  File "main.py", line 32, in do_work
KeyError: 'name'
[5608] Failed to execute script 'main' due to unhandled exception!

[已退出进程，代码为 1]
**Screenshots**
插入程序出现BUG的截图
![屏幕截图 2022-04-05 105020](https://user-images.githubusercontent.com/62222561/161670086-1f88cc46-40e0-4314-bafb-60b2eef5e303.png)
**运行环境 (请完善以下信息):**
 - 系统：Windows11家庭中文版21H2 操作系统版本22000.556 [比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:Python3.9 [比如:Python2,Python3.6,Python3.8]
 - 运行方式:  可执行文件exe运行 [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:2.3.0 [比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内、容

**Comment by Samueli924** [comment]
感谢反馈，该问题已修复完毕，可以下载最新的[Release](https://github.com/Samueli924/chaoxing/releases/tag/2.3.0)

**Comment by 1578339936** [comment]
![图片](https://user-images.githubusercontent.com/62222561/161871673-c3388831-c6d0-4cce-9f6b-dffa255cf638.png)
新的问题
