### ISSUE TITLE
[BUG反馈]源码运行错误

### ISSUE THREAD

**Issue by 1578339936** [Samueli924/chaoxing#56]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
Traceback (most recent call last):
  File "K:\chaoxing-main\main.py", line 65, in <module>
    ft.init_all_path(["saves", "logs"])  # 检查文件夹
  File "K:\chaoxing-main\utils\functions.py", line 56, in init_all_path
    check_path(path, file=False)
  File "K:\chaoxing-main\utils\functions.py", line 50, in check_path
    mkdir(path)
PermissionError: [WinError 5] 拒绝访问。: 'saves'
[已退出进程，代码为 1]
**Screenshots**
插入程序出现BUG的截图
![屏幕截图 2022-04-05 105927](https://user-images.githubusercontent.com/62222561/161670346-d3115b29-2746-49c1-ba48-ba4c2df18b0a.png)
**运行环境 (请完善以下信息):**
 - 系统：Windows11家庭中文版21H2 操作系统版本22000.556 [比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:Python3.9 [比如:Python2,Python3.6,Python3.8]
 - 运行方式:  源代码运行 [比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:2.3.0 [比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内、容

**Comment by Samueli924** [comment]
这个我无法确定问题出在哪。   

------  

你可以尝试  

------  

1. 删除代码路径下的saves和logs文件夹  
2. 使用管理员身份运行代码

**Comment by 1578339936** [comment]
1.这两个文件夹并没有出现。
2.以管理员身份运行不会报错也不会运行
![图片](https://user-images.githubusercontent.com/62222561/161766263-77b5af8a-f426-4ea3-8f9f-8498ddd6fe35.png)
如图，纯英文路径反应相同

**Comment by Samueli924** [comment]
那不用powershell而是用管理员运行cmd呢

如果管理员运行cmd也不行，那你可以尝试直接用打包好的exe运行

**Comment by 1578339936** [comment]
收到，已经切换成exe了
