### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by tangboys** [Samueli924/chaoxing#57]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：win11[比如:Windows,macOS,Linux(精确到发行版本名)]
 - Python环境版本:Python3.6[比如:Python2,Python3.6,Python3.8]
 - 运行方式: 源码运行和可执行文件exe[比如:源代码运行,可执行文件exe运行,打包bat文件运行]
 - 代码版本:2.3.0[比如0.5.0,1.0.0]

**其他内容**
您觉得对问题反馈有帮助的内容
如果第一个没有完成就会完成第一个然后就提示报错
如果第一个完成了就直接报错
![QQ图片20220405123145](https://user-images.githubusercontent.com/89062640/161679263-4dd8a830-bdf7-47ec-93ac-026daa7a3821.png)

**Comment by Samueli924** [comment]
你好 感谢反馈。请使用最新的[2.3.1版本exe文件](https://github.com/Samueli924/chaoxing/releases/tag/2.3.1)
