### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by anpolarbear** [Samueli924/chaoxing#65]
出现报错<class 'KeyError'>
错误文件名：C:\Users\user\Downloads\chaoxing-2.3.2\main.py
错误行数：86
错误原因:'jobid'
请截图提交至Github或Telegram供作者修改代码
点击回车键退出程序

**Comment by Samueli924** [comment]
在之前的反馈中推测是视频格式没有适配，已加入更新计划中。
