### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by FinleyGe** [Samueli924/chaoxing#67]
main.py 86行，Json解析错误

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/32237950/162717746-2d566566-befa-4935-902f-8d87b1f0b77f.png)

**运行环境 (请完善以下信息):**
 - 系统：Ubuntu 20.04.4
 - Python 3.8.10
 - 运行方式: screen 中 `python main.py`
 - 代码版本: 2.3.1

**Comment by Samueli924** [comment]
已修复
