### ISSUE TITLE
[Advice]

### ISSUE THREAD

**Issue by L-zee** [Samueli924/chaoxing#74]
**清晰有逻辑的提出问题**
详细内容
![image](https://user-images.githubusercontent.com/45615832/163327334-4723763c-0301-4ee3-b323-88196fb75380.png)
多次进入学习通客户端，未发现有验证码验证。

**Comment by huajijam** [comment]
请更新至新版本重试并提交日志

**Comment by L-zee** [comment]
![image](https://user-images.githubusercontent.com/45615832/163584883-4f13e55d-d8a1-468d-9d96-e8fba7d5e30a.png)

![image](https://user-images.githubusercontent.com/45615832/163584970-4d282fb1-b6fa-4243-9d80-fbb4da957ea3.png)
有较大概率复现，但日志并无详细记录，甚至无法找到截图中提到的C:\Users\Meteors\AppData\Local\Temp\_MEI149282文件夹

**Comment by huajijam** [comment]
请更新至新源码运行重试并提交日志
