### ISSUE TITLE
使用python3.7运行程序报错

### ISSUE THREAD

**Issue by OxfordProfessor** [Samueli924/chaoxing#80]
**形容Bug的信息**
Bug出现在chaoxing.py文件中第127行

**Screenshots**
![image](https://user-images.githubusercontent.com/77258835/163673638-b909464b-535f-42ad-88b2-b364d0d5bf7a.png)
![image](https://user-images.githubusercontent.com/77258835/163673700-ffda2aa7-56df-4829-9645-25456a31bc7f.png)

**运行环境 (请完善以下信息):**
 - 系统：Win10家庭中文版 21H2版本
 - Python环境版本:Python3.7
 - 运行方式: cmd命令行python main.py执行
 - 代码版本:2.3.5版本

**Comment by Samueli924** [comment]
代码需要在python3.9及以上版本运行。 :=是python3.9以后才有的功能
