### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by L-zee** [Samueli924/chaoxing#81]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
![image](https://user-images.githubusercontent.com/45615832/163667080-91cee9f6-ee81-41ad-9d16-5b54726901da.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows 19044.1645
 - 运行方式: exe运行
 - 代码版本:2.3.5

**Comment by lyj0309** [comment]
应该是开了代理，不要开代理

**Comment by L-zee** [comment]
不知道为什么，在运行过程中多次开启/关闭代理，暂时无法复现此问题。
