### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by ghost** [Samueli924/chaoxing#82]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/103501206/163739900-dec9b159-65ff-4cf6-a61c-03deef6da191.png)

**运行环境 (请完善以下信息):**
 - 系统：win11专业版22000.613
 - 运行方式: exe运行
 - 代码版本:2,3,5

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 3013238989** [comment]
到最后一个任务视频 显示完成,没有完成,报错
