### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by 3013238989** [Samueli924/chaoxing#83]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
退出出错
**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/103501206/163741134-b007d5d3-409c-4fdc-8054-f8f5b8a2fec2.png)

**运行环境 (请完善以下信息):**
 - 系统：win11专业版21H2 22000.613
 - 运行方式: exe运行
 - 代码版本:2,3,5

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 3013238989** [comment]
没有验证码

**Comment by huajijam** [comment]
请更新至新源码运行重试并提交日志
