### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by shenjiabao0813** [Samueli924/chaoxing#84]
![image](https://user-images.githubusercontent.com/93148554/163817940-075b00ba-d544-4789-969c-b9b05a217423.png)
登录不了

**Comment by L-zee** [comment]
我也遇到同样问题，使用2.3.5版本和2.3.4版本均无法登录
![image](https://user-images.githubusercontent.com/45615832/163840371-89fa8f62-cc74-411d-a3f7-a19f4936ee74.png)

**Comment by huajijam** [comment]
请更新至最新代码版本运行并携带log反馈

**Comment by shenjiabao0813** [comment]
> 

更新代码后可用了，再次感谢
