### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Zaker-hso** [Samueli924/chaoxing#85]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容
全新安装，无法登录
**Screenshots**
插入程序出现BUG的截图
![image](https://user-images.githubusercontent.com/68645177/163835167-64eacf8b-529c-4d6c-8d92-9496f67427df.png)

**运行环境 (请完善以下信息):**
 - 系统：centos7
 - Python环境版本:python3.9
 - 运行方式: 源代码运行
 - 代码版本:least

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by 3013238989** [comment]
![image](https://user-images.githubusercontent.com/103501206/163836825-979c1b9e-8a18-41d1-887c-2062b96a0b92.png)

**Comment by huajijam** [comment]
请更新至最新代码版本运行并携带log反馈

**Comment by Zaker-hso** [comment]
更新至最新代码版本后已经可以正常使用，感谢！
