### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by lichunjian21** [Samueli924/chaoxing#86]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
![image](https://user-images.githubusercontent.com/83053553/163915616-15209b97-e1f9-4e49-8585-f33b04883ee6.png)

插入程序出现BUG的截图

**运行环境 (请完善以下信息):**
 - 系统：win11 企业版 21H2
 - Python环境版本:python3.8
 - 运行方式: 可执行文件exe运行
 - 代码版本:2.5.4

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Moxiner** [comment]
### 描述
我在Debug的时候追溯到这里，由于我对 requests 库 并不是很了解，剩下的只能交给作者了
### 代码 
```
发生异常: JSONDecodeError
Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

  File "[C:\Users\Via\Desktop\chaoxing-2.3.5\api\chaoxing.py]()", line 69, in get_all_courses
    courses = self.session.get(url).json()
  File "[C:\Users\Via\Desktop\chaoxing-2.3.5\main.py]()", line 76, in <module>
    if chaoxing.get_all_courses():  # 读取所有的课程
```
### 截图
![Bug截图](https://s1.ax1x.com/2022/04/19/LBMFAK.png)

**Comment by Moxiner** [comment]
### 原因
终于找到原因了
我打印了 courses 的输出值，很显然，回执失败，返回值无法Json化，于是导致软件报错
```
请输入要登录的用户序号，新建请输入直接点击回车键1
2022-04-19 16:57:38,407 - main - INFO - 开始登录
2022-04-19 16:57:38,551 - main - INFO - 开始读取所有课程
<Response [403]>
```
### 截图
![截图](https://s1.ax1x.com/2022/04/19/LB8wff.png)

**Comment by huajijam** [comment]
请更新至最新代码版本运行并携带log反馈

**Comment by chloe357** [comment]
[ChaoxingAPI.log](https://github.com/Samueli924/chaoxing/files/8552851/ChaoxingAPI.log)
[main.log](https://github.com/Samueli924/chaoxing/files/8552853/main.log)
![image](https://user-images.githubusercontent.com/73072850/165051221-690e8c61-bff0-4d21-a81a-8f3295f8dc84.png)
每次到这个就卡住了
