### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Keviince** [Samueli924/chaoxing#93]
**形容Bug的信息**
错误行数：169
错误原因：'function' object has no attribute 'sleep'

**Screenshots**
![QQ图片20220424140558](https://user-images.githubusercontent.com/32187894/164959038-6c7f132e-5cc1-400c-8409-575b6179917d.png)

**运行环境 (请完善以下信息):**
 - 系统：CentOS Stream 8
 - Python环境版本:Python 3.10.4
 - 运行方式: 源代码运行
 - 代码版本: 2.3.7

**其他内容**
尝试过把main.py第49行的ft.time.sleep(1)替换为系统的time.sleep(1)但并无作用

**Comment by lhy1118** [comment]
修改 api/chaoxing.py  main.py  utils/function.py 这三个文件，增加一个包from time import sleep，再将搜索所有用到sleep的地方，全部改为sleep(时间)

**Comment by Keviince** [comment]
> 修改 api/chaoxing.py main.py utils/function.py 这三个文件，增加一个包from time import sleep，再将搜索所有用到sleep的地方，全部改为sleep(时间)

经过修改，问题已解决，感谢
