### ISSUE TITLE
[BUG反馈]function' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by whl2606555** [Samueli924/chaoxing#94]
错误文件名：/root/chaoxing/main.py
错误行数：169
错误原因:'function' object has no attribute 'sleep'

**Comment by Samueli924** [comment]
已修复，请拉取最新源码使用

**Comment by whl2606555** [comment]
修复的故障点似乎不对，刚才我也对源码做了和git上相同的修改，发现故障依旧，拉取最新源码故障也是依旧。

**Comment by Samueli924** [comment]
我这边修复好了哈，之前有个Collaborator提交Commit的变量名起的是time。。
