### ISSUE TITLE
[BUG反馈]刷课出现权限问题，但无论是在web还是客户端都可以正常使用

### ISSUE THREAD

**Issue by Hetols** [Samueli924/chaoxing#96]
**形容Bug的信息**
清楚准确的描述Bug出现的代码行数，以及上下文的日志内容

**Screenshots**
插入程序出现BUG的截图
请输入您要学习的课程序号：3
默认倍速： 1 倍速
在不紧急的情况下建议使用 1 倍速，因使用不合理的多倍速造成的一 切风险与作者无关
请输入您想要的学习倍速(倍数需为整数,0或直接回车将使用默认倍速)：
2022-04-26 08:32:09,556 - main - INFO - 已使用默认速率
是否启用自适应速率(当播放速率为1且视频支持倍速播放时,自动切换 为两倍速)
！注意 该功能可能存在风险！输入(Y/y/Yes/yes)启用
2022-04-26 08:32:10,819 - main - INFO - 已禁用自适应速率
2022-04-26 08:32:10,820 - main - INFO - 开始学习
2022-04-26 08:32:10,821 - main - INFO - 已选课程：军事理论
2022-04-26 08:32:10,821 - main - INFO - 开始获取所有章节
开始读取标签信息

当前章节：1.1:国防的内涵

当前视频：1.1.mp4
当前播放速率：1倍速
出现报错<class 'requests.exceptions.JSONDecodeError'>
错误文件名：/root/chaoxing/chaoxing/main.py
错误行数：169
错误原因:[Errno Expecting value] <!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>403</title>
<style>
.main{height:255px;margin:0 auto;margin-top:15%;font-size:14px;color:#999; width: 350px;}
.font_top{padding-top:45px;display:inline;}
</style>
</head>
<body>
<div class="main">
<p class="font_top">>_< 【9011】很抱歉，您没有权限访问这个页面！code=1  (403)</p>
<p style="font-size: 12px; color: #ddd;">112.96.54.163<br/>mooc-3818821160-lrhdr</p>
</div>
</body>
</html>
: 0
请截图提交至Github或Telegram供作者修改代码

**运行环境 (请完善以下信息):**
 - 系统: Ubuntu 21.10
 - Python环境版本: Python3.10.4
 - 运行方式: 源代码运行
 - 代码版本: 2.3.8 in 20220404

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
你好 BUG已修复 请拉取最新的源码或使用最新的exe可执行文件
