### ISSUE TITLE
增加复习模式

### ISSUE THREAD

**Issue by Summmmmmary** [Samueli924/chaoxing#97]
新增功能：增加复习模式
以前99999倍过的，虽然超星没有清除异常课程，但后台显示13/1068min，就挺离谱的
但是现有版本（只限于本项目）检测任务点完成后默认跳过，所以希望增加此功能，谢谢作者！

**Comment by Samueli924** [comment]
哈哈哈哈哈哈哈哈哈你这不是一般的离谱

**Comment by Samueli924** [comment]
![IMG_20220426_234620](https://user-images.githubusercontent.com/65054820/165340250-7fc2cb82-2c18-4b0e-8384-e83f13af947b.jpg)
你把源码main.py的第46-50行的内容注释掉再运行就好了，你这个着实属于个例，单独开发个功能不是那么有必要的。

**Comment by Summmmmmary** [comment]
爱你呦 :)

**Comment by Summmmmmary** [comment]
不可以呀，不可以，这段注释了也不行

**Comment by Samueli924** [comment]
已在群中回复
