### ISSUE TITLE
增加定时退出功能

### ISSUE THREAD

**Issue by Summmmmmary** [Samueli924/chaoxing#99]
部分学校（比如我）有超星的阅读学分，一天上限50分，所以忘了关就凉凉了（因为已完成任务点重复刷后续不计时长）
也就加个判断的事，希望作者版本更新的时候考虑一下哦 
要是会py我就直接写了，可惜我是个web前端 :)

**Comment by d4renk** [comment]
**cron 自己写个杀进程呗**

**Comment by Samueli924** [comment]
好的 未来版本会添加这个可选参数
